// This file is auto-generated by generateDataLoader.js
// Do not modify manually.

import data1992_1 from '../data/1992/1.json';
import data1992_2 from '../data/1992/2.json';
import data1992_3 from '../data/1992/3.json';
import data1992_4 from '../data/1992/4.json';
import data1992_5 from '../data/1992/5.json';
import data1992_6 from '../data/1992/6.json';
import data1992_7 from '../data/1992/7.json';
import data1992_8 from '../data/1992/8.json';
import data1992_9 from '../data/1992/9.json';
import data1992_10 from '../data/1992/10.json';
import data1992_11 from '../data/1992/11.json';
import data1992_12 from '../data/1992/12.json';

import data1993_1 from '../data/1993/1.json';
import data1993_2 from '../data/1993/2.json';
import data1993_3 from '../data/1993/3.json';
import data1993_4 from '../data/1993/4.json';
import data1993_5 from '../data/1993/5.json';
import data1993_6 from '../data/1993/6.json';
import data1993_7 from '../data/1993/7.json';
import data1993_8 from '../data/1993/8.json';
import data1993_9 from '../data/1993/9.json';
import data1993_10 from '../data/1993/10.json';
import data1993_11 from '../data/1993/11.json';
import data1993_12 from '../data/1993/12.json';

import data1994_1 from '../data/1994/1.json';
import data1994_2 from '../data/1994/2.json';
import data1994_3 from '../data/1994/3.json';
import data1994_4 from '../data/1994/4.json';
import data1994_5 from '../data/1994/5.json';
import data1994_6 from '../data/1994/6.json';
import data1994_7 from '../data/1994/7.json';
import data1994_8 from '../data/1994/8.json';
import data1994_9 from '../data/1994/9.json';
import data1994_10 from '../data/1994/10.json';
import data1994_11 from '../data/1994/11.json';
import data1994_12 from '../data/1994/12.json';

import data1995_1 from '../data/1995/1.json';
import data1995_2 from '../data/1995/2.json';
import data1995_3 from '../data/1995/3.json';
import data1995_4 from '../data/1995/4.json';
import data1995_5 from '../data/1995/5.json';
import data1995_6 from '../data/1995/6.json';
import data1995_7 from '../data/1995/7.json';
import data1995_8 from '../data/1995/8.json';
import data1995_9 from '../data/1995/9.json';
import data1995_10 from '../data/1995/10.json';
import data1995_11 from '../data/1995/11.json';
import data1995_12 from '../data/1995/12.json';

import data1996_1 from '../data/1996/1.json';
import data1996_2 from '../data/1996/2.json';
import data1996_3 from '../data/1996/3.json';
import data1996_4 from '../data/1996/4.json';
import data1996_5 from '../data/1996/5.json';
import data1996_6 from '../data/1996/6.json';
import data1996_7 from '../data/1996/7.json';
import data1996_8 from '../data/1996/8.json';
import data1996_9 from '../data/1996/9.json';
import data1996_10 from '../data/1996/10.json';
import data1996_11 from '../data/1996/11.json';
import data1996_12 from '../data/1996/12.json';

import data1997_1 from '../data/1997/1.json';
import data1997_2 from '../data/1997/2.json';
import data1997_3 from '../data/1997/3.json';
import data1997_4 from '../data/1997/4.json';
import data1997_5 from '../data/1997/5.json';
import data1997_6 from '../data/1997/6.json';
import data1997_7 from '../data/1997/7.json';
import data1997_8 from '../data/1997/8.json';
import data1997_9 from '../data/1997/9.json';
import data1997_10 from '../data/1997/10.json';
import data1997_11 from '../data/1997/11.json';
import data1997_12 from '../data/1997/12.json';

import data1998_1 from '../data/1998/1.json';
import data1998_2 from '../data/1998/2.json';
import data1998_3 from '../data/1998/3.json';
import data1998_4 from '../data/1998/4.json';
import data1998_5 from '../data/1998/5.json';
import data1998_6 from '../data/1998/6.json';
import data1998_7 from '../data/1998/7.json';
import data1998_8 from '../data/1998/8.json';
import data1998_9 from '../data/1998/9.json';
import data1998_10 from '../data/1998/10.json';
import data1998_11 from '../data/1998/11.json';
import data1998_12 from '../data/1998/12.json';

import data1999_1 from '../data/1999/1.json';
import data1999_2 from '../data/1999/2.json';
import data1999_3 from '../data/1999/3.json';
import data1999_4 from '../data/1999/4.json';
import data1999_5 from '../data/1999/5.json';
import data1999_6 from '../data/1999/6.json';
import data1999_7 from '../data/1999/7.json';
import data1999_8 from '../data/1999/8.json';
import data1999_9 from '../data/1999/9.json';
import data1999_10 from '../data/1999/10.json';
import data1999_11 from '../data/1999/11.json';
import data1999_12 from '../data/1999/12.json';

import data2000_1 from '../data/2000/1.json';
import data2000_2 from '../data/2000/2.json';
import data2000_3 from '../data/2000/3.json';
import data2000_4 from '../data/2000/4.json';
import data2000_5 from '../data/2000/5.json';
import data2000_6 from '../data/2000/6.json';
import data2000_7 from '../data/2000/7.json';
import data2000_8 from '../data/2000/8.json';
import data2000_9 from '../data/2000/9.json';
import data2000_10 from '../data/2000/10.json';
import data2000_11 from '../data/2000/11.json';
import data2000_12 from '../data/2000/12.json';

import data2001_1 from '../data/2001/1.json';
import data2001_2 from '../data/2001/2.json';
import data2001_3 from '../data/2001/3.json';
import data2001_4 from '../data/2001/4.json';
import data2001_5 from '../data/2001/5.json';
import data2001_6 from '../data/2001/6.json';
import data2001_7 from '../data/2001/7.json';
import data2001_8 from '../data/2001/8.json';
import data2001_9 from '../data/2001/9.json';
import data2001_10 from '../data/2001/10.json';
import data2001_11 from '../data/2001/11.json';
import data2001_12 from '../data/2001/12.json';

import data2002_1 from '../data/2002/1.json';
import data2002_2 from '../data/2002/2.json';
import data2002_3 from '../data/2002/3.json';
import data2002_4 from '../data/2002/4.json';
import data2002_5 from '../data/2002/5.json';
import data2002_6 from '../data/2002/6.json';
import data2002_7 from '../data/2002/7.json';
import data2002_8 from '../data/2002/8.json';
import data2002_9 from '../data/2002/9.json';
import data2002_10 from '../data/2002/10.json';
import data2002_11 from '../data/2002/11.json';
import data2002_12 from '../data/2002/12.json';

import data2003_1 from '../data/2003/1.json';
import data2003_2 from '../data/2003/2.json';
import data2003_3 from '../data/2003/3.json';
import data2003_4 from '../data/2003/4.json';
import data2003_5 from '../data/2003/5.json';
import data2003_6 from '../data/2003/6.json';
import data2003_7 from '../data/2003/7.json';
import data2003_8 from '../data/2003/8.json';
import data2003_9 from '../data/2003/9.json';
import data2003_10 from '../data/2003/10.json';
import data2003_11 from '../data/2003/11.json';
import data2003_12 from '../data/2003/12.json';

import data2004_1 from '../data/2004/1.json';
import data2004_2 from '../data/2004/2.json';
import data2004_3 from '../data/2004/3.json';
import data2004_4 from '../data/2004/4.json';
import data2004_5 from '../data/2004/5.json';
import data2004_6 from '../data/2004/6.json';
import data2004_7 from '../data/2004/7.json';
import data2004_8 from '../data/2004/8.json';
import data2004_9 from '../data/2004/9.json';
import data2004_10 from '../data/2004/10.json';
import data2004_11 from '../data/2004/11.json';
import data2004_12 from '../data/2004/12.json';

import data2005_1 from '../data/2005/1.json';
import data2005_2 from '../data/2005/2.json';
import data2005_3 from '../data/2005/3.json';
import data2005_4 from '../data/2005/4.json';
import data2005_5 from '../data/2005/5.json';
import data2005_6 from '../data/2005/6.json';
import data2005_7 from '../data/2005/7.json';
import data2005_8 from '../data/2005/8.json';
import data2005_9 from '../data/2005/9.json';
import data2005_10 from '../data/2005/10.json';
import data2005_11 from '../data/2005/11.json';
import data2005_12 from '../data/2005/12.json';

import data2006_1 from '../data/2006/1.json';
import data2006_2 from '../data/2006/2.json';
import data2006_3 from '../data/2006/3.json';
import data2006_4 from '../data/2006/4.json';
import data2006_5 from '../data/2006/5.json';
import data2006_6 from '../data/2006/6.json';
import data2006_7 from '../data/2006/7.json';
import data2006_8 from '../data/2006/8.json';
import data2006_9 from '../data/2006/9.json';
import data2006_10 from '../data/2006/10.json';
import data2006_11 from '../data/2006/11.json';
import data2006_12 from '../data/2006/12.json';

import data2007_1 from '../data/2007/1.json';
import data2007_2 from '../data/2007/2.json';
import data2007_3 from '../data/2007/3.json';
import data2007_4 from '../data/2007/4.json';
import data2007_5 from '../data/2007/5.json';
import data2007_6 from '../data/2007/6.json';
import data2007_7 from '../data/2007/7.json';
import data2007_8 from '../data/2007/8.json';
import data2007_9 from '../data/2007/9.json';
import data2007_10 from '../data/2007/10.json';
import data2007_11 from '../data/2007/11.json';
import data2007_12 from '../data/2007/12.json';

import data2008_1 from '../data/2008/1.json';
import data2008_2 from '../data/2008/2.json';
import data2008_3 from '../data/2008/3.json';
import data2008_4 from '../data/2008/4.json';
import data2008_5 from '../data/2008/5.json';
import data2008_6 from '../data/2008/6.json';
import data2008_7 from '../data/2008/7.json';
import data2008_8 from '../data/2008/8.json';
import data2008_9 from '../data/2008/9.json';
import data2008_10 from '../data/2008/10.json';
import data2008_11 from '../data/2008/11.json';
import data2008_12 from '../data/2008/12.json';

import data2009_1 from '../data/2009/1.json';
import data2009_2 from '../data/2009/2.json';
import data2009_3 from '../data/2009/3.json';
import data2009_4 from '../data/2009/4.json';
import data2009_5 from '../data/2009/5.json';
import data2009_6 from '../data/2009/6.json';
import data2009_7 from '../data/2009/7.json';
import data2009_8 from '../data/2009/8.json';
import data2009_9 from '../data/2009/9.json';
import data2009_10 from '../data/2009/10.json';
import data2009_11 from '../data/2009/11.json';
import data2009_12 from '../data/2009/12.json';

import data2010_1 from '../data/2010/1.json';
import data2010_2 from '../data/2010/2.json';
import data2010_3 from '../data/2010/3.json';
import data2010_4 from '../data/2010/4.json';
import data2010_5 from '../data/2010/5.json';
import data2010_6 from '../data/2010/6.json';
import data2010_7 from '../data/2010/7.json';
import data2010_8 from '../data/2010/8.json';
import data2010_9 from '../data/2010/9.json';
import data2010_10 from '../data/2010/10.json';
import data2010_11 from '../data/2010/11.json';
import data2010_12 from '../data/2010/12.json';

import data2011_1 from '../data/2011/1.json';
import data2011_2 from '../data/2011/2.json';
import data2011_3 from '../data/2011/3.json';
import data2011_4 from '../data/2011/4.json';
import data2011_5 from '../data/2011/5.json';
import data2011_6 from '../data/2011/6.json';
import data2011_7 from '../data/2011/7.json';
import data2011_8 from '../data/2011/8.json';
import data2011_9 from '../data/2011/9.json';
import data2011_10 from '../data/2011/10.json';
import data2011_11 from '../data/2011/11.json';
import data2011_12 from '../data/2011/12.json';

import data2012_1 from '../data/2012/1.json';
import data2012_2 from '../data/2012/2.json';
import data2012_3 from '../data/2012/3.json';
import data2012_4 from '../data/2012/4.json';
import data2012_5 from '../data/2012/5.json';
import data2012_6 from '../data/2012/6.json';
import data2012_7 from '../data/2012/7.json';
import data2012_8 from '../data/2012/8.json';
import data2012_9 from '../data/2012/9.json';
import data2012_10 from '../data/2012/10.json';
import data2012_11 from '../data/2012/11.json';
import data2012_12 from '../data/2012/12.json';

import data2013_1 from '../data/2013/1.json';
import data2013_2 from '../data/2013/2.json';
import data2013_3 from '../data/2013/3.json';
import data2013_4 from '../data/2013/4.json';
import data2013_5 from '../data/2013/5.json';
import data2013_6 from '../data/2013/6.json';
import data2013_7 from '../data/2013/7.json';
import data2013_8 from '../data/2013/8.json';
import data2013_9 from '../data/2013/9.json';
import data2013_10 from '../data/2013/10.json';
import data2013_11 from '../data/2013/11.json';
import data2013_12 from '../data/2013/12.json';

import data2014_1 from '../data/2014/1.json';
import data2014_2 from '../data/2014/2.json';
import data2014_3 from '../data/2014/3.json';
import data2014_4 from '../data/2014/4.json';
import data2014_5 from '../data/2014/5.json';
import data2014_6 from '../data/2014/6.json';
import data2014_7 from '../data/2014/7.json';
import data2014_8 from '../data/2014/8.json';
import data2014_9 from '../data/2014/9.json';
import data2014_10 from '../data/2014/10.json';
import data2014_11 from '../data/2014/11.json';
import data2014_12 from '../data/2014/12.json';

import data2015_1 from '../data/2015/1.json';
import data2015_2 from '../data/2015/2.json';
import data2015_3 from '../data/2015/3.json';
import data2015_4 from '../data/2015/4.json';
import data2015_5 from '../data/2015/5.json';
import data2015_6 from '../data/2015/6.json';
import data2015_7 from '../data/2015/7.json';
import data2015_8 from '../data/2015/8.json';
import data2015_9 from '../data/2015/9.json';
import data2015_10 from '../data/2015/10.json';
import data2015_11 from '../data/2015/11.json';
import data2015_12 from '../data/2015/12.json';

import data2016_1 from '../data/2016/1.json';
import data2016_2 from '../data/2016/2.json';
import data2016_3 from '../data/2016/3.json';
import data2016_4 from '../data/2016/4.json';
import data2016_5 from '../data/2016/5.json';
import data2016_6 from '../data/2016/6.json';
import data2016_7 from '../data/2016/7.json';
import data2016_8 from '../data/2016/8.json';
import data2016_9 from '../data/2016/9.json';
import data2016_10 from '../data/2016/10.json';
import data2016_11 from '../data/2016/11.json';
import data2016_12 from '../data/2016/12.json';

import data2017_1 from '../data/2017/1.json';
import data2017_2 from '../data/2017/2.json';
import data2017_3 from '../data/2017/3.json';
import data2017_4 from '../data/2017/4.json';
import data2017_5 from '../data/2017/5.json';
import data2017_6 from '../data/2017/6.json';
import data2017_7 from '../data/2017/7.json';
import data2017_8 from '../data/2017/8.json';
import data2017_9 from '../data/2017/9.json';
import data2017_10 from '../data/2017/10.json';
import data2017_11 from '../data/2017/11.json';
import data2017_12 from '../data/2017/12.json';

import data2018_1 from '../data/2018/1.json';
import data2018_2 from '../data/2018/2.json';
import data2018_3 from '../data/2018/3.json';
import data2018_4 from '../data/2018/4.json';
import data2018_5 from '../data/2018/5.json';
import data2018_6 from '../data/2018/6.json';
import data2018_7 from '../data/2018/7.json';
import data2018_8 from '../data/2018/8.json';
import data2018_9 from '../data/2018/9.json';
import data2018_10 from '../data/2018/10.json';
import data2018_11 from '../data/2018/11.json';
import data2018_12 from '../data/2018/12.json';

import data2019_1 from '../data/2019/1.json';
import data2019_2 from '../data/2019/2.json';
import data2019_3 from '../data/2019/3.json';
import data2019_4 from '../data/2019/4.json';
import data2019_5 from '../data/2019/5.json';
import data2019_6 from '../data/2019/6.json';
import data2019_7 from '../data/2019/7.json';
import data2019_8 from '../data/2019/8.json';
import data2019_9 from '../data/2019/9.json';
import data2019_10 from '../data/2019/10.json';
import data2019_11 from '../data/2019/11.json';
import data2019_12 from '../data/2019/12.json';

import data2020_1 from '../data/2020/1.json';
import data2020_2 from '../data/2020/2.json';
import data2020_3 from '../data/2020/3.json';
import data2020_4 from '../data/2020/4.json';
import data2020_5 from '../data/2020/5.json';
import data2020_6 from '../data/2020/6.json';
import data2020_7 from '../data/2020/7.json';
import data2020_8 from '../data/2020/8.json';
import data2020_9 from '../data/2020/9.json';
import data2020_10 from '../data/2020/10.json';
import data2020_11 from '../data/2020/11.json';
import data2020_12 from '../data/2020/12.json';

import data2021_1 from '../data/2021/1.json';
import data2021_2 from '../data/2021/2.json';
import data2021_3 from '../data/2021/3.json';
import data2021_4 from '../data/2021/4.json';
import data2021_5 from '../data/2021/5.json';
import data2021_6 from '../data/2021/6.json';
import data2021_7 from '../data/2021/7.json';
import data2021_8 from '../data/2021/8.json';
import data2021_9 from '../data/2021/9.json';
import data2021_10 from '../data/2021/10.json';
import data2021_11 from '../data/2021/11.json';
import data2021_12 from '../data/2021/12.json';

import data2022_1 from '../data/2022/1.json';
import data2022_2 from '../data/2022/2.json';
import data2022_3 from '../data/2022/3.json';
import data2022_4 from '../data/2022/4.json';
import data2022_5 from '../data/2022/5.json';
import data2022_6 from '../data/2022/6.json';
import data2022_7 from '../data/2022/7.json';
import data2022_8 from '../data/2022/8.json';
import data2022_9 from '../data/2022/9.json';
import data2022_10 from '../data/2022/10.json';
import data2022_11 from '../data/2022/11.json';
import data2022_12 from '../data/2022/12.json';

import data2023_1 from '../data/2023/1.json';
import data2023_2 from '../data/2023/2.json';
import data2023_3 from '../data/2023/3.json';
import data2023_4 from '../data/2023/4.json';
import data2023_5 from '../data/2023/5.json';
import data2023_6 from '../data/2023/6.json';
import data2023_7 from '../data/2023/7.json';
import data2023_8 from '../data/2023/8.json';
import data2023_9 from '../data/2023/9.json';
import data2023_10 from '../data/2023/10.json';
import data2023_11 from '../data/2023/11.json';
import data2023_12 from '../data/2023/12.json';

import data2024_1 from '../data/2024/1.json';
import data2024_2 from '../data/2024/2.json';
import data2024_3 from '../data/2024/3.json';
import data2024_4 from '../data/2024/4.json';
import data2024_5 from '../data/2024/5.json';
import data2024_6 from '../data/2024/6.json';
import data2024_7 from '../data/2024/7.json';
import data2024_8 from '../data/2024/8.json';
import data2024_9 from '../data/2024/9.json';
import data2024_10 from '../data/2024/10.json';
import data2024_11 from '../data/2024/11.json';
import data2024_12 from '../data/2024/12.json';

import data2025_1 from '../data/2025/1.json';
import data2025_2 from '../data/2025/2.json';
import data2025_3 from '../data/2025/3.json';
import data2025_4 from '../data/2025/4.json';
import data2025_5 from '../data/2025/5.json';
import data2025_6 from '../data/2025/6.json';
import data2025_7 from '../data/2025/7.json';
import data2025_8 from '../data/2025/8.json';
import data2025_9 from '../data/2025/9.json';
import data2025_10 from '../data/2025/10.json';
import data2025_11 from '../data/2025/11.json';
import data2025_12 from '../data/2025/12.json';

import data2026_1 from '../data/2026/1.json';
import data2026_2 from '../data/2026/2.json';
import data2026_3 from '../data/2026/3.json';
import data2026_4 from '../data/2026/4.json';
import data2026_5 from '../data/2026/5.json';
import data2026_6 from '../data/2026/6.json';
import data2026_7 from '../data/2026/7.json';
import data2026_8 from '../data/2026/8.json';
import data2026_9 from '../data/2026/9.json';
import data2026_10 from '../data/2026/10.json';
import data2026_11 from '../data/2026/11.json';
import data2026_12 from '../data/2026/12.json';

import data2027_1 from '../data/2027/1.json';
import data2027_2 from '../data/2027/2.json';
import data2027_3 from '../data/2027/3.json';
import data2027_4 from '../data/2027/4.json';
import data2027_5 from '../data/2027/5.json';
import data2027_6 from '../data/2027/6.json';
import data2027_7 from '../data/2027/7.json';
import data2027_8 from '../data/2027/8.json';
import data2027_9 from '../data/2027/9.json';
import data2027_10 from '../data/2027/10.json';
import data2027_11 from '../data/2027/11.json';
import data2027_12 from '../data/2027/12.json';

import data2028_1 from '../data/2028/1.json';
import data2028_2 from '../data/2028/2.json';
import data2028_3 from '../data/2028/3.json';
import data2028_4 from '../data/2028/4.json';
import data2028_5 from '../data/2028/5.json';
import data2028_6 from '../data/2028/6.json';
import data2028_7 from '../data/2028/7.json';
import data2028_8 from '../data/2028/8.json';
import data2028_9 from '../data/2028/9.json';
import data2028_10 from '../data/2028/10.json';
import data2028_11 from '../data/2028/11.json';
import data2028_12 from '../data/2028/12.json';

import data2029_1 from '../data/2029/1.json';
import data2029_2 from '../data/2029/2.json';
import data2029_3 from '../data/2029/3.json';
import data2029_4 from '../data/2029/4.json';
import data2029_5 from '../data/2029/5.json';
import data2029_6 from '../data/2029/6.json';
import data2029_7 from '../data/2029/7.json';
import data2029_8 from '../data/2029/8.json';
import data2029_9 from '../data/2029/9.json';
import data2029_10 from '../data/2029/10.json';
import data2029_11 from '../data/2029/11.json';
import data2029_12 from '../data/2029/12.json';

import data2030_1 from '../data/2030/1.json';
import data2030_2 from '../data/2030/2.json';
import data2030_3 from '../data/2030/3.json';
import data2030_4 from '../data/2030/4.json';
import data2030_5 from '../data/2030/5.json';
import data2030_6 from '../data/2030/6.json';
import data2030_7 from '../data/2030/7.json';
import data2030_8 from '../data/2030/8.json';
import data2030_9 from '../data/2030/9.json';
import data2030_10 from '../data/2030/10.json';
import data2030_11 from '../data/2030/11.json';
import data2030_12 from '../data/2030/12.json';

import data2031_1 from '../data/2031/1.json';
import data2031_2 from '../data/2031/2.json';
import data2031_3 from '../data/2031/3.json';
import data2031_4 from '../data/2031/4.json';
import data2031_5 from '../data/2031/5.json';
import data2031_6 from '../data/2031/6.json';
import data2031_7 from '../data/2031/7.json';
import data2031_8 from '../data/2031/8.json';
import data2031_9 from '../data/2031/9.json';
import data2031_10 from '../data/2031/10.json';
import data2031_11 from '../data/2031/11.json';
import data2031_12 from '../data/2031/12.json';

import data2032_1 from '../data/2032/1.json';
import data2032_2 from '../data/2032/2.json';
import data2032_3 from '../data/2032/3.json';
import data2032_4 from '../data/2032/4.json';
import data2032_5 from '../data/2032/5.json';
import data2032_6 from '../data/2032/6.json';
import data2032_7 from '../data/2032/7.json';
import data2032_8 from '../data/2032/8.json';
import data2032_9 from '../data/2032/9.json';
import data2032_10 from '../data/2032/10.json';
import data2032_11 from '../data/2032/11.json';
import data2032_12 from '../data/2032/12.json';

import data2033_1 from '../data/2033/1.json';
import data2033_2 from '../data/2033/2.json';
import data2033_3 from '../data/2033/3.json';
import data2033_4 from '../data/2033/4.json';
import data2033_5 from '../data/2033/5.json';
import data2033_6 from '../data/2033/6.json';
import data2033_7 from '../data/2033/7.json';
import data2033_8 from '../data/2033/8.json';
import data2033_9 from '../data/2033/9.json';
import data2033_10 from '../data/2033/10.json';
import data2033_11 from '../data/2033/11.json';
import data2033_12 from '../data/2033/12.json';

import data2034_1 from '../data/2034/1.json';
import data2034_2 from '../data/2034/2.json';
import data2034_3 from '../data/2034/3.json';
import data2034_4 from '../data/2034/4.json';
import data2034_5 from '../data/2034/5.json';
import data2034_6 from '../data/2034/6.json';
import data2034_7 from '../data/2034/7.json';
import data2034_8 from '../data/2034/8.json';
import data2034_9 from '../data/2034/9.json';
import data2034_10 from '../data/2034/10.json';
import data2034_11 from '../data/2034/11.json';
import data2034_12 from '../data/2034/12.json';

import data2035_1 from '../data/2035/1.json';
import data2035_2 from '../data/2035/2.json';
import data2035_3 from '../data/2035/3.json';
import data2035_4 from '../data/2035/4.json';
import data2035_5 from '../data/2035/5.json';
import data2035_6 from '../data/2035/6.json';
import data2035_7 from '../data/2035/7.json';
import data2035_8 from '../data/2035/8.json';
import data2035_9 from '../data/2035/9.json';
import data2035_10 from '../data/2035/10.json';
import data2035_11 from '../data/2035/11.json';
import data2035_12 from '../data/2035/12.json';

import data2036_1 from '../data/2036/1.json';
import data2036_2 from '../data/2036/2.json';
import data2036_3 from '../data/2036/3.json';
import data2036_4 from '../data/2036/4.json';
import data2036_5 from '../data/2036/5.json';
import data2036_6 from '../data/2036/6.json';
import data2036_7 from '../data/2036/7.json';
import data2036_8 from '../data/2036/8.json';
import data2036_9 from '../data/2036/9.json';
import data2036_10 from '../data/2036/10.json';
import data2036_11 from '../data/2036/11.json';
import data2036_12 from '../data/2036/12.json';

import data2037_1 from '../data/2037/1.json';
import data2037_2 from '../data/2037/2.json';
import data2037_3 from '../data/2037/3.json';
import data2037_4 from '../data/2037/4.json';
import data2037_5 from '../data/2037/5.json';
import data2037_6 from '../data/2037/6.json';
import data2037_7 from '../data/2037/7.json';
import data2037_8 from '../data/2037/8.json';
import data2037_9 from '../data/2037/9.json';
import data2037_10 from '../data/2037/10.json';
import data2037_11 from '../data/2037/11.json';
import data2037_12 from '../data/2037/12.json';

import data2038_1 from '../data/2038/1.json';
import data2038_2 from '../data/2038/2.json';
import data2038_3 from '../data/2038/3.json';
import data2038_4 from '../data/2038/4.json';
import data2038_5 from '../data/2038/5.json';
import data2038_6 from '../data/2038/6.json';
import data2038_7 from '../data/2038/7.json';
import data2038_8 from '../data/2038/8.json';
import data2038_9 from '../data/2038/9.json';
import data2038_10 from '../data/2038/10.json';
import data2038_11 from '../data/2038/11.json';
import data2038_12 from '../data/2038/12.json';

import data2039_1 from '../data/2039/1.json';
import data2039_2 from '../data/2039/2.json';
import data2039_3 from '../data/2039/3.json';
import data2039_4 from '../data/2039/4.json';
import data2039_5 from '../data/2039/5.json';
import data2039_6 from '../data/2039/6.json';
import data2039_7 from '../data/2039/7.json';
import data2039_8 from '../data/2039/8.json';
import data2039_9 from '../data/2039/9.json';
import data2039_10 from '../data/2039/10.json';
import data2039_11 from '../data/2039/11.json';
import data2039_12 from '../data/2039/12.json';

import data2040_1 from '../data/2040/1.json';
import data2040_2 from '../data/2040/2.json';
import data2040_3 from '../data/2040/3.json';
import data2040_4 from '../data/2040/4.json';
import data2040_5 from '../data/2040/5.json';
import data2040_6 from '../data/2040/6.json';
import data2040_7 from '../data/2040/7.json';
import data2040_8 from '../data/2040/8.json';
import data2040_9 from '../data/2040/9.json';
import data2040_10 from '../data/2040/10.json';
import data2040_11 from '../data/2040/11.json';
import data2040_12 from '../data/2040/12.json';

import data2041_1 from '../data/2041/1.json';
import data2041_2 from '../data/2041/2.json';
import data2041_3 from '../data/2041/3.json';
import data2041_4 from '../data/2041/4.json';
import data2041_5 from '../data/2041/5.json';
import data2041_6 from '../data/2041/6.json';
import data2041_7 from '../data/2041/7.json';
import data2041_8 from '../data/2041/8.json';
import data2041_9 from '../data/2041/9.json';
import data2041_10 from '../data/2041/10.json';
import data2041_11 from '../data/2041/11.json';
import data2041_12 from '../data/2041/12.json';

import data2042_1 from '../data/2042/1.json';
import data2042_2 from '../data/2042/2.json';
import data2042_3 from '../data/2042/3.json';
import data2042_4 from '../data/2042/4.json';
import data2042_5 from '../data/2042/5.json';
import data2042_6 from '../data/2042/6.json';
import data2042_7 from '../data/2042/7.json';
import data2042_8 from '../data/2042/8.json';
import data2042_9 from '../data/2042/9.json';
import data2042_10 from '../data/2042/10.json';
import data2042_11 from '../data/2042/11.json';
import data2042_12 from '../data/2042/12.json';

import data2043_1 from '../data/2043/1.json';
import data2043_2 from '../data/2043/2.json';
import data2043_3 from '../data/2043/3.json';
import data2043_4 from '../data/2043/4.json';
import data2043_5 from '../data/2043/5.json';
import data2043_6 from '../data/2043/6.json';
import data2043_7 from '../data/2043/7.json';
import data2043_8 from '../data/2043/8.json';
import data2043_9 from '../data/2043/9.json';
import data2043_10 from '../data/2043/10.json';
import data2043_11 from '../data/2043/11.json';
import data2043_12 from '../data/2043/12.json';

import data2044_1 from '../data/2044/1.json';
import data2044_2 from '../data/2044/2.json';
import data2044_3 from '../data/2044/3.json';
import data2044_4 from '../data/2044/4.json';
import data2044_5 from '../data/2044/5.json';
import data2044_6 from '../data/2044/6.json';
import data2044_7 from '../data/2044/7.json';
import data2044_8 from '../data/2044/8.json';
import data2044_9 from '../data/2044/9.json';
import data2044_10 from '../data/2044/10.json';
import data2044_11 from '../data/2044/11.json';
import data2044_12 from '../data/2044/12.json';

import data2045_1 from '../data/2045/1.json';
import data2045_2 from '../data/2045/2.json';
import data2045_3 from '../data/2045/3.json';
import data2045_4 from '../data/2045/4.json';
import data2045_5 from '../data/2045/5.json';
import data2045_6 from '../data/2045/6.json';
import data2045_7 from '../data/2045/7.json';
import data2045_8 from '../data/2045/8.json';
import data2045_9 from '../data/2045/9.json';
import data2045_10 from '../data/2045/10.json';
import data2045_11 from '../data/2045/11.json';
import data2045_12 from '../data/2045/12.json';

import data2046_1 from '../data/2046/1.json';
import data2046_2 from '../data/2046/2.json';
import data2046_3 from '../data/2046/3.json';
import data2046_4 from '../data/2046/4.json';
import data2046_5 from '../data/2046/5.json';
import data2046_6 from '../data/2046/6.json';
import data2046_7 from '../data/2046/7.json';
import data2046_8 from '../data/2046/8.json';
import data2046_9 from '../data/2046/9.json';
import data2046_10 from '../data/2046/10.json';
import data2046_11 from '../data/2046/11.json';
import data2046_12 from '../data/2046/12.json';

import data2047_1 from '../data/2047/1.json';
import data2047_2 from '../data/2047/2.json';
import data2047_3 from '../data/2047/3.json';
import data2047_4 from '../data/2047/4.json';
import data2047_5 from '../data/2047/5.json';
import data2047_6 from '../data/2047/6.json';
import data2047_7 from '../data/2047/7.json';
import data2047_8 from '../data/2047/8.json';
import data2047_9 from '../data/2047/9.json';
import data2047_10 from '../data/2047/10.json';
import data2047_11 from '../data/2047/11.json';
import data2047_12 from '../data/2047/12.json';

import data2048_1 from '../data/2048/1.json';
import data2048_2 from '../data/2048/2.json';
import data2048_3 from '../data/2048/3.json';
import data2048_4 from '../data/2048/4.json';
import data2048_5 from '../data/2048/5.json';
import data2048_6 from '../data/2048/6.json';
import data2048_7 from '../data/2048/7.json';
import data2048_8 from '../data/2048/8.json';
import data2048_9 from '../data/2048/9.json';
import data2048_10 from '../data/2048/10.json';
import data2048_11 from '../data/2048/11.json';
import data2048_12 from '../data/2048/12.json';

import data2049_1 from '../data/2049/1.json';
import data2049_2 from '../data/2049/2.json';
import data2049_3 from '../data/2049/3.json';
import data2049_4 from '../data/2049/4.json';
import data2049_5 from '../data/2049/5.json';
import data2049_6 from '../data/2049/6.json';
import data2049_7 from '../data/2049/7.json';
import data2049_8 from '../data/2049/8.json';
import data2049_9 from '../data/2049/9.json';
import data2049_10 from '../data/2049/10.json';
import data2049_11 from '../data/2049/11.json';
import data2049_12 from '../data/2049/12.json';

import data2050_1 from '../data/2050/1.json';
import data2050_2 from '../data/2050/2.json';
import data2050_3 from '../data/2050/3.json';
import data2050_4 from '../data/2050/4.json';
import data2050_5 from '../data/2050/5.json';
import data2050_6 from '../data/2050/6.json';
import data2050_7 from '../data/2050/7.json';
import data2050_8 from '../data/2050/8.json';
import data2050_9 from '../data/2050/9.json';
import data2050_10 from '../data/2050/10.json';
import data2050_11 from '../data/2050/11.json';
import data2050_12 from '../data/2050/12.json';

import data2051_1 from '../data/2051/1.json';
import data2051_2 from '../data/2051/2.json';
import data2051_3 from '../data/2051/3.json';
import data2051_4 from '../data/2051/4.json';
import data2051_5 from '../data/2051/5.json';
import data2051_6 from '../data/2051/6.json';
import data2051_7 from '../data/2051/7.json';
import data2051_8 from '../data/2051/8.json';
import data2051_9 from '../data/2051/9.json';
import data2051_10 from '../data/2051/10.json';
import data2051_11 from '../data/2051/11.json';
import data2051_12 from '../data/2051/12.json';

import data2052_1 from '../data/2052/1.json';
import data2052_2 from '../data/2052/2.json';
import data2052_3 from '../data/2052/3.json';
import data2052_4 from '../data/2052/4.json';
import data2052_5 from '../data/2052/5.json';
import data2052_6 from '../data/2052/6.json';
import data2052_7 from '../data/2052/7.json';
import data2052_8 from '../data/2052/8.json';
import data2052_9 from '../data/2052/9.json';
import data2052_10 from '../data/2052/10.json';
import data2052_11 from '../data/2052/11.json';
import data2052_12 from '../data/2052/12.json';

import data2053_1 from '../data/2053/1.json';
import data2053_2 from '../data/2053/2.json';
import data2053_3 from '../data/2053/3.json';
import data2053_4 from '../data/2053/4.json';
import data2053_5 from '../data/2053/5.json';
import data2053_6 from '../data/2053/6.json';
import data2053_7 from '../data/2053/7.json';
import data2053_8 from '../data/2053/8.json';
import data2053_9 from '../data/2053/9.json';
import data2053_10 from '../data/2053/10.json';
import data2053_11 from '../data/2053/11.json';
import data2053_12 from '../data/2053/12.json';

import data2054_1 from '../data/2054/1.json';
import data2054_2 from '../data/2054/2.json';
import data2054_3 from '../data/2054/3.json';
import data2054_4 from '../data/2054/4.json';
import data2054_5 from '../data/2054/5.json';
import data2054_6 from '../data/2054/6.json';
import data2054_7 from '../data/2054/7.json';
import data2054_8 from '../data/2054/8.json';
import data2054_9 from '../data/2054/9.json';
import data2054_10 from '../data/2054/10.json';
import data2054_11 from '../data/2054/11.json';
import data2054_12 from '../data/2054/12.json';

import data2055_1 from '../data/2055/1.json';
import data2055_2 from '../data/2055/2.json';
import data2055_3 from '../data/2055/3.json';
import data2055_4 from '../data/2055/4.json';
import data2055_5 from '../data/2055/5.json';
import data2055_6 from '../data/2055/6.json';
import data2055_7 from '../data/2055/7.json';
import data2055_8 from '../data/2055/8.json';
import data2055_9 from '../data/2055/9.json';
import data2055_10 from '../data/2055/10.json';
import data2055_11 from '../data/2055/11.json';
import data2055_12 from '../data/2055/12.json';

import data2056_1 from '../data/2056/1.json';
import data2056_2 from '../data/2056/2.json';
import data2056_3 from '../data/2056/3.json';
import data2056_4 from '../data/2056/4.json';
import data2056_5 from '../data/2056/5.json';
import data2056_6 from '../data/2056/6.json';
import data2056_7 from '../data/2056/7.json';
import data2056_8 from '../data/2056/8.json';
import data2056_9 from '../data/2056/9.json';
import data2056_10 from '../data/2056/10.json';
import data2056_11 from '../data/2056/11.json';
import data2056_12 from '../data/2056/12.json';

import data2057_1 from '../data/2057/1.json';
import data2057_2 from '../data/2057/2.json';
import data2057_3 from '../data/2057/3.json';
import data2057_4 from '../data/2057/4.json';
import data2057_5 from '../data/2057/5.json';
import data2057_6 from '../data/2057/6.json';
import data2057_7 from '../data/2057/7.json';
import data2057_8 from '../data/2057/8.json';
import data2057_9 from '../data/2057/9.json';
import data2057_10 from '../data/2057/10.json';
import data2057_11 from '../data/2057/11.json';
import data2057_12 from '../data/2057/12.json';

import data2058_1 from '../data/2058/1.json';
import data2058_2 from '../data/2058/2.json';
import data2058_3 from '../data/2058/3.json';
import data2058_4 from '../data/2058/4.json';
import data2058_5 from '../data/2058/5.json';
import data2058_6 from '../data/2058/6.json';
import data2058_7 from '../data/2058/7.json';
import data2058_8 from '../data/2058/8.json';
import data2058_9 from '../data/2058/9.json';
import data2058_10 from '../data/2058/10.json';
import data2058_11 from '../data/2058/11.json';
import data2058_12 from '../data/2058/12.json';

import data2059_1 from '../data/2059/1.json';
import data2059_2 from '../data/2059/2.json';
import data2059_3 from '../data/2059/3.json';
import data2059_4 from '../data/2059/4.json';
import data2059_5 from '../data/2059/5.json';
import data2059_6 from '../data/2059/6.json';
import data2059_7 from '../data/2059/7.json';
import data2059_8 from '../data/2059/8.json';
import data2059_9 from '../data/2059/9.json';
import data2059_10 from '../data/2059/10.json';
import data2059_11 from '../data/2059/11.json';
import data2059_12 from '../data/2059/12.json';

import data2060_1 from '../data/2060/1.json';
import data2060_2 from '../data/2060/2.json';
import data2060_3 from '../data/2060/3.json';
import data2060_4 from '../data/2060/4.json';
import data2060_5 from '../data/2060/5.json';
import data2060_6 from '../data/2060/6.json';
import data2060_7 from '../data/2060/7.json';
import data2060_8 from '../data/2060/8.json';
import data2060_9 from '../data/2060/9.json';
import data2060_10 from '../data/2060/10.json';
import data2060_11 from '../data/2060/11.json';
import data2060_12 from '../data/2060/12.json';

import data2061_1 from '../data/2061/1.json';
import data2061_2 from '../data/2061/2.json';
import data2061_3 from '../data/2061/3.json';
import data2061_4 from '../data/2061/4.json';
import data2061_5 from '../data/2061/5.json';
import data2061_6 from '../data/2061/6.json';
import data2061_7 from '../data/2061/7.json';
import data2061_8 from '../data/2061/8.json';
import data2061_9 from '../data/2061/9.json';
import data2061_10 from '../data/2061/10.json';
import data2061_11 from '../data/2061/11.json';
import data2061_12 from '../data/2061/12.json';

import data2062_1 from '../data/2062/1.json';
import data2062_2 from '../data/2062/2.json';
import data2062_3 from '../data/2062/3.json';
import data2062_4 from '../data/2062/4.json';
import data2062_5 from '../data/2062/5.json';
import data2062_6 from '../data/2062/6.json';
import data2062_7 from '../data/2062/7.json';
import data2062_8 from '../data/2062/8.json';
import data2062_9 from '../data/2062/9.json';
import data2062_10 from '../data/2062/10.json';
import data2062_11 from '../data/2062/11.json';
import data2062_12 from '../data/2062/12.json';

import data2063_1 from '../data/2063/1.json';
import data2063_2 from '../data/2063/2.json';
import data2063_3 from '../data/2063/3.json';
import data2063_4 from '../data/2063/4.json';
import data2063_5 from '../data/2063/5.json';
import data2063_6 from '../data/2063/6.json';
import data2063_7 from '../data/2063/7.json';
import data2063_8 from '../data/2063/8.json';
import data2063_9 from '../data/2063/9.json';
import data2063_10 from '../data/2063/10.json';
import data2063_11 from '../data/2063/11.json';
import data2063_12 from '../data/2063/12.json';

import data2064_1 from '../data/2064/1.json';
import data2064_2 from '../data/2064/2.json';
import data2064_3 from '../data/2064/3.json';
import data2064_4 from '../data/2064/4.json';
import data2064_5 from '../data/2064/5.json';
import data2064_6 from '../data/2064/6.json';
import data2064_7 from '../data/2064/7.json';
import data2064_8 from '../data/2064/8.json';
import data2064_9 from '../data/2064/9.json';
import data2064_10 from '../data/2064/10.json';
import data2064_11 from '../data/2064/11.json';
import data2064_12 from '../data/2064/12.json';

import data2065_1 from '../data/2065/1.json';
import data2065_2 from '../data/2065/2.json';
import data2065_3 from '../data/2065/3.json';
import data2065_4 from '../data/2065/4.json';
import data2065_5 from '../data/2065/5.json';
import data2065_6 from '../data/2065/6.json';
import data2065_7 from '../data/2065/7.json';
import data2065_8 from '../data/2065/8.json';
import data2065_9 from '../data/2065/9.json';
import data2065_10 from '../data/2065/10.json';
import data2065_11 from '../data/2065/11.json';
import data2065_12 from '../data/2065/12.json';

import data2066_1 from '../data/2066/1.json';
import data2066_2 from '../data/2066/2.json';
import data2066_3 from '../data/2066/3.json';
import data2066_4 from '../data/2066/4.json';
import data2066_5 from '../data/2066/5.json';
import data2066_6 from '../data/2066/6.json';
import data2066_7 from '../data/2066/7.json';
import data2066_8 from '../data/2066/8.json';
import data2066_9 from '../data/2066/9.json';
import data2066_10 from '../data/2066/10.json';
import data2066_11 from '../data/2066/11.json';
import data2066_12 from '../data/2066/12.json';

import data2067_1 from '../data/2067/1.json';
import data2067_2 from '../data/2067/2.json';
import data2067_3 from '../data/2067/3.json';
import data2067_4 from '../data/2067/4.json';
import data2067_5 from '../data/2067/5.json';
import data2067_6 from '../data/2067/6.json';
import data2067_7 from '../data/2067/7.json';
import data2067_8 from '../data/2067/8.json';
import data2067_9 from '../data/2067/9.json';
import data2067_10 from '../data/2067/10.json';
import data2067_11 from '../data/2067/11.json';
import data2067_12 from '../data/2067/12.json';

import data2068_1 from '../data/2068/1.json';
import data2068_2 from '../data/2068/2.json';
import data2068_3 from '../data/2068/3.json';
import data2068_4 from '../data/2068/4.json';
import data2068_5 from '../data/2068/5.json';
import data2068_6 from '../data/2068/6.json';
import data2068_7 from '../data/2068/7.json';
import data2068_8 from '../data/2068/8.json';
import data2068_9 from '../data/2068/9.json';
import data2068_10 from '../data/2068/10.json';
import data2068_11 from '../data/2068/11.json';
import data2068_12 from '../data/2068/12.json';

import data2069_1 from '../data/2069/1.json';
import data2069_2 from '../data/2069/2.json';
import data2069_3 from '../data/2069/3.json';
import data2069_4 from '../data/2069/4.json';
import data2069_5 from '../data/2069/5.json';
import data2069_6 from '../data/2069/6.json';
import data2069_7 from '../data/2069/7.json';
import data2069_8 from '../data/2069/8.json';
import data2069_9 from '../data/2069/9.json';
import data2069_10 from '../data/2069/10.json';
import data2069_11 from '../data/2069/11.json';
import data2069_12 from '../data/2069/12.json';

import data2070_1 from '../data/2070/1.json';
import data2070_2 from '../data/2070/2.json';
import data2070_3 from '../data/2070/3.json';
import data2070_4 from '../data/2070/4.json';
import data2070_5 from '../data/2070/5.json';
import data2070_6 from '../data/2070/6.json';
import data2070_7 from '../data/2070/7.json';
import data2070_8 from '../data/2070/8.json';
import data2070_9 from '../data/2070/9.json';
import data2070_10 from '../data/2070/10.json';
import data2070_11 from '../data/2070/11.json';
import data2070_12 from '../data/2070/12.json';

import data2071_1 from '../data/2071/1.json';
import data2071_2 from '../data/2071/2.json';
import data2071_3 from '../data/2071/3.json';
import data2071_4 from '../data/2071/4.json';
import data2071_5 from '../data/2071/5.json';
import data2071_6 from '../data/2071/6.json';
import data2071_7 from '../data/2071/7.json';
import data2071_8 from '../data/2071/8.json';
import data2071_9 from '../data/2071/9.json';
import data2071_10 from '../data/2071/10.json';
import data2071_11 from '../data/2071/11.json';
import data2071_12 from '../data/2071/12.json';

import data2072_1 from '../data/2072/1.json';
import data2072_2 from '../data/2072/2.json';
import data2072_3 from '../data/2072/3.json';
import data2072_4 from '../data/2072/4.json';
import data2072_5 from '../data/2072/5.json';
import data2072_6 from '../data/2072/6.json';
import data2072_7 from '../data/2072/7.json';
import data2072_8 from '../data/2072/8.json';
import data2072_9 from '../data/2072/9.json';
import data2072_10 from '../data/2072/10.json';
import data2072_11 from '../data/2072/11.json';
import data2072_12 from '../data/2072/12.json';

import data2073_1 from '../data/2073/1.json';
import data2073_2 from '../data/2073/2.json';
import data2073_3 from '../data/2073/3.json';
import data2073_4 from '../data/2073/4.json';
import data2073_5 from '../data/2073/5.json';
import data2073_6 from '../data/2073/6.json';
import data2073_7 from '../data/2073/7.json';
import data2073_8 from '../data/2073/8.json';
import data2073_9 from '../data/2073/9.json';
import data2073_10 from '../data/2073/10.json';
import data2073_11 from '../data/2073/11.json';
import data2073_12 from '../data/2073/12.json';

import data2074_1 from '../data/2074/1.json';
import data2074_2 from '../data/2074/2.json';
import data2074_3 from '../data/2074/3.json';
import data2074_4 from '../data/2074/4.json';
import data2074_5 from '../data/2074/5.json';
import data2074_6 from '../data/2074/6.json';
import data2074_7 from '../data/2074/7.json';
import data2074_8 from '../data/2074/8.json';
import data2074_9 from '../data/2074/9.json';
import data2074_10 from '../data/2074/10.json';
import data2074_11 from '../data/2074/11.json';
import data2074_12 from '../data/2074/12.json';

import data2075_1 from '../data/2075/1.json';
import data2075_2 from '../data/2075/2.json';
import data2075_3 from '../data/2075/3.json';
import data2075_4 from '../data/2075/4.json';
import data2075_5 from '../data/2075/5.json';
import data2075_6 from '../data/2075/6.json';
import data2075_7 from '../data/2075/7.json';
import data2075_8 from '../data/2075/8.json';
import data2075_9 from '../data/2075/9.json';
import data2075_10 from '../data/2075/10.json';
import data2075_11 from '../data/2075/11.json';
import data2075_12 from '../data/2075/12.json';

import data2076_1 from '../data/2076/1.json';
import data2076_2 from '../data/2076/2.json';
import data2076_3 from '../data/2076/3.json';
import data2076_4 from '../data/2076/4.json';
import data2076_5 from '../data/2076/5.json';
import data2076_6 from '../data/2076/6.json';
import data2076_7 from '../data/2076/7.json';
import data2076_8 from '../data/2076/8.json';
import data2076_9 from '../data/2076/9.json';
import data2076_10 from '../data/2076/10.json';
import data2076_11 from '../data/2076/11.json';
import data2076_12 from '../data/2076/12.json';

import data2077_1 from '../data/2077/1.json';
import data2077_2 from '../data/2077/2.json';
import data2077_3 from '../data/2077/3.json';
import data2077_4 from '../data/2077/4.json';
import data2077_5 from '../data/2077/5.json';
import data2077_6 from '../data/2077/6.json';
import data2077_7 from '../data/2077/7.json';
import data2077_8 from '../data/2077/8.json';
import data2077_9 from '../data/2077/9.json';
import data2077_10 from '../data/2077/10.json';
import data2077_11 from '../data/2077/11.json';
import data2077_12 from '../data/2077/12.json';

import data2078_1 from '../data/2078/1.json';
import data2078_2 from '../data/2078/2.json';
import data2078_3 from '../data/2078/3.json';
import data2078_4 from '../data/2078/4.json';
import data2078_5 from '../data/2078/5.json';
import data2078_6 from '../data/2078/6.json';
import data2078_7 from '../data/2078/7.json';
import data2078_8 from '../data/2078/8.json';
import data2078_9 from '../data/2078/9.json';
import data2078_10 from '../data/2078/10.json';
import data2078_11 from '../data/2078/11.json';
import data2078_12 from '../data/2078/12.json';

import data2079_1 from '../data/2079/1.json';
import data2079_2 from '../data/2079/2.json';
import data2079_3 from '../data/2079/3.json';
import data2079_4 from '../data/2079/4.json';
import data2079_5 from '../data/2079/5.json';
import data2079_6 from '../data/2079/6.json';
import data2079_7 from '../data/2079/7.json';
import data2079_8 from '../data/2079/8.json';
import data2079_9 from '../data/2079/9.json';
import data2079_10 from '../data/2079/10.json';
import data2079_11 from '../data/2079/11.json';
import data2079_12 from '../data/2079/12.json';

import data2080_1 from '../data/2080/1.json';
import data2080_2 from '../data/2080/2.json';
import data2080_3 from '../data/2080/3.json';
import data2080_4 from '../data/2080/4.json';
import data2080_5 from '../data/2080/5.json';
import data2080_6 from '../data/2080/6.json';
import data2080_7 from '../data/2080/7.json';
import data2080_8 from '../data/2080/8.json';
import data2080_9 from '../data/2080/9.json';
import data2080_10 from '../data/2080/10.json';
import data2080_11 from '../data/2080/11.json';
import data2080_12 from '../data/2080/12.json';

import data2081_1 from '../data/2081/1.json';
import data2081_2 from '../data/2081/2.json';
import data2081_3 from '../data/2081/3.json';
import data2081_4 from '../data/2081/4.json';
import data2081_5 from '../data/2081/5.json';
import data2081_6 from '../data/2081/6.json';
import data2081_7 from '../data/2081/7.json';
import data2081_8 from '../data/2081/8.json';
import data2081_9 from '../data/2081/9.json';
import data2081_10 from '../data/2081/10.json';
import data2081_11 from '../data/2081/11.json';
import data2081_12 from '../data/2081/12.json';

import data2082_1 from '../data/2082/1.json';
import data2082_2 from '../data/2082/2.json';
import data2082_3 from '../data/2082/3.json';
import data2082_4 from '../data/2082/4.json';
import data2082_5 from '../data/2082/5.json';
import data2082_6 from '../data/2082/6.json';
import data2082_7 from '../data/2082/7.json';
import data2082_8 from '../data/2082/8.json';
import data2082_9 from '../data/2082/9.json';
import data2082_10 from '../data/2082/10.json';
import data2082_11 from '../data/2082/11.json';
import data2082_12 from '../data/2082/12.json';

import data2083_1 from '../data/2083/1.json';
import data2083_2 from '../data/2083/2.json';
import data2083_3 from '../data/2083/3.json';
import data2083_4 from '../data/2083/4.json';
import data2083_5 from '../data/2083/5.json';
import data2083_6 from '../data/2083/6.json';
import data2083_7 from '../data/2083/7.json';
import data2083_8 from '../data/2083/8.json';
import data2083_9 from '../data/2083/9.json';
import data2083_10 from '../data/2083/10.json';
import data2083_11 from '../data/2083/11.json';
import data2083_12 from '../data/2083/12.json';

import data2084_1 from '../data/2084/1.json';
import data2084_2 from '../data/2084/2.json';
import data2084_3 from '../data/2084/3.json';
import data2084_4 from '../data/2084/4.json';
import data2084_5 from '../data/2084/5.json';
import data2084_6 from '../data/2084/6.json';
import data2084_7 from '../data/2084/7.json';
import data2084_8 from '../data/2084/8.json';
import data2084_9 from '../data/2084/9.json';
import data2084_10 from '../data/2084/10.json';
import data2084_11 from '../data/2084/11.json';
import data2084_12 from '../data/2084/12.json';

import data2085_1 from '../data/2085/1.json';
import data2085_2 from '../data/2085/2.json';
import data2085_3 from '../data/2085/3.json';
import data2085_4 from '../data/2085/4.json';
import data2085_5 from '../data/2085/5.json';
import data2085_6 from '../data/2085/6.json';
import data2085_7 from '../data/2085/7.json';
import data2085_8 from '../data/2085/8.json';
import data2085_9 from '../data/2085/9.json';
import data2085_10 from '../data/2085/10.json';
import data2085_11 from '../data/2085/11.json';
import data2085_12 from '../data/2085/12.json';

import data2086_1 from '../data/2086/1.json';
import data2086_2 from '../data/2086/2.json';
import data2086_3 from '../data/2086/3.json';
import data2086_4 from '../data/2086/4.json';
import data2086_5 from '../data/2086/5.json';
import data2086_6 from '../data/2086/6.json';
import data2086_7 from '../data/2086/7.json';
import data2086_8 from '../data/2086/8.json';
import data2086_9 from '../data/2086/9.json';
import data2086_10 from '../data/2086/10.json';
import data2086_11 from '../data/2086/11.json';
import data2086_12 from '../data/2086/12.json';

import data2087_1 from '../data/2087/1.json';
import data2087_2 from '../data/2087/2.json';
import data2087_3 from '../data/2087/3.json';
import data2087_4 from '../data/2087/4.json';
import data2087_5 from '../data/2087/5.json';
import data2087_6 from '../data/2087/6.json';
import data2087_7 from '../data/2087/7.json';
import data2087_8 from '../data/2087/8.json';
import data2087_9 from '../data/2087/9.json';
import data2087_10 from '../data/2087/10.json';
import data2087_11 from '../data/2087/11.json';
import data2087_12 from '../data/2087/12.json';

import data2088_1 from '../data/2088/1.json';
import data2088_2 from '../data/2088/2.json';
import data2088_3 from '../data/2088/3.json';
import data2088_4 from '../data/2088/4.json';
import data2088_5 from '../data/2088/5.json';
import data2088_6 from '../data/2088/6.json';
import data2088_7 from '../data/2088/7.json';
import data2088_8 from '../data/2088/8.json';
import data2088_9 from '../data/2088/9.json';
import data2088_10 from '../data/2088/10.json';
import data2088_11 from '../data/2088/11.json';
import data2088_12 from '../data/2088/12.json';

import data2089_1 from '../data/2089/1.json';
import data2089_2 from '../data/2089/2.json';
import data2089_3 from '../data/2089/3.json';
import data2089_4 from '../data/2089/4.json';
import data2089_5 from '../data/2089/5.json';
import data2089_6 from '../data/2089/6.json';
import data2089_7 from '../data/2089/7.json';
import data2089_8 from '../data/2089/8.json';
import data2089_9 from '../data/2089/9.json';
import data2089_10 from '../data/2089/10.json';
import data2089_11 from '../data/2089/11.json';
import data2089_12 from '../data/2089/12.json';

import data2090_1 from '../data/2090/1.json';
import data2090_2 from '../data/2090/2.json';
import data2090_3 from '../data/2090/3.json';
import data2090_4 from '../data/2090/4.json';
import data2090_5 from '../data/2090/5.json';
import data2090_6 from '../data/2090/6.json';
import data2090_7 from '../data/2090/7.json';
import data2090_8 from '../data/2090/8.json';
import data2090_9 from '../data/2090/9.json';
import data2090_10 from '../data/2090/10.json';
import data2090_11 from '../data/2090/11.json';
import data2090_12 from '../data/2090/12.json';

import data2091_1 from '../data/2091/1.json';
import data2091_2 from '../data/2091/2.json';
import data2091_3 from '../data/2091/3.json';
import data2091_4 from '../data/2091/4.json';
import data2091_5 from '../data/2091/5.json';
import data2091_6 from '../data/2091/6.json';
import data2091_7 from '../data/2091/7.json';
import data2091_8 from '../data/2091/8.json';
import data2091_9 from '../data/2091/9.json';
import data2091_10 from '../data/2091/10.json';
import data2091_11 from '../data/2091/11.json';
import data2091_12 from '../data/2091/12.json';

import data2092_1 from '../data/2092/1.json';
import data2092_2 from '../data/2092/2.json';
import data2092_3 from '../data/2092/3.json';
import data2092_4 from '../data/2092/4.json';
import data2092_5 from '../data/2092/5.json';
import data2092_6 from '../data/2092/6.json';
import data2092_7 from '../data/2092/7.json';
import data2092_8 from '../data/2092/8.json';
import data2092_9 from '../data/2092/9.json';
import data2092_10 from '../data/2092/10.json';
import data2092_11 from '../data/2092/11.json';
import data2092_12 from '../data/2092/12.json';

import data2093_1 from '../data/2093/1.json';
import data2093_2 from '../data/2093/2.json';
import data2093_3 from '../data/2093/3.json';
import data2093_4 from '../data/2093/4.json';
import data2093_5 from '../data/2093/5.json';
import data2093_6 from '../data/2093/6.json';
import data2093_7 from '../data/2093/7.json';
import data2093_8 from '../data/2093/8.json';
import data2093_9 from '../data/2093/9.json';
import data2093_10 from '../data/2093/10.json';
import data2093_11 from '../data/2093/11.json';
import data2093_12 from '../data/2093/12.json';

import data2094_1 from '../data/2094/1.json';
import data2094_2 from '../data/2094/2.json';
import data2094_3 from '../data/2094/3.json';
import data2094_4 from '../data/2094/4.json';
import data2094_5 from '../data/2094/5.json';
import data2094_6 from '../data/2094/6.json';
import data2094_7 from '../data/2094/7.json';
import data2094_8 from '../data/2094/8.json';
import data2094_9 from '../data/2094/9.json';
import data2094_10 from '../data/2094/10.json';
import data2094_11 from '../data/2094/11.json';
import data2094_12 from '../data/2094/12.json';

import data2095_1 from '../data/2095/1.json';
import data2095_2 from '../data/2095/2.json';
import data2095_3 from '../data/2095/3.json';
import data2095_4 from '../data/2095/4.json';
import data2095_5 from '../data/2095/5.json';
import data2095_6 from '../data/2095/6.json';
import data2095_7 from '../data/2095/7.json';
import data2095_8 from '../data/2095/8.json';
import data2095_9 from '../data/2095/9.json';
import data2095_10 from '../data/2095/10.json';
import data2095_11 from '../data/2095/11.json';
import data2095_12 from '../data/2095/12.json';

import data2096_1 from '../data/2096/1.json';
import data2096_2 from '../data/2096/2.json';
import data2096_3 from '../data/2096/3.json';
import data2096_4 from '../data/2096/4.json';
import data2096_5 from '../data/2096/5.json';
import data2096_6 from '../data/2096/6.json';
import data2096_7 from '../data/2096/7.json';
import data2096_8 from '../data/2096/8.json';
import data2096_9 from '../data/2096/9.json';
import data2096_10 from '../data/2096/10.json';
import data2096_11 from '../data/2096/11.json';
import data2096_12 from '../data/2096/12.json';

import data2097_1 from '../data/2097/1.json';
import data2097_2 from '../data/2097/2.json';
import data2097_3 from '../data/2097/3.json';
import data2097_4 from '../data/2097/4.json';
import data2097_5 from '../data/2097/5.json';
import data2097_6 from '../data/2097/6.json';
import data2097_7 from '../data/2097/7.json';
import data2097_8 from '../data/2097/8.json';
import data2097_9 from '../data/2097/9.json';
import data2097_10 from '../data/2097/10.json';
import data2097_11 from '../data/2097/11.json';
import data2097_12 from '../data/2097/12.json';

import data2098_1 from '../data/2098/1.json';
import data2098_2 from '../data/2098/2.json';
import data2098_3 from '../data/2098/3.json';
import data2098_4 from '../data/2098/4.json';
import data2098_5 from '../data/2098/5.json';
import data2098_6 from '../data/2098/6.json';
import data2098_7 from '../data/2098/7.json';
import data2098_8 from '../data/2098/8.json';
import data2098_9 from '../data/2098/9.json';
import data2098_10 from '../data/2098/10.json';
import data2098_11 from '../data/2098/11.json';
import data2098_12 from '../data/2098/12.json';

import data2099_1 from '../data/2099/1.json';
import data2099_2 from '../data/2099/2.json';
import data2099_3 from '../data/2099/3.json';
import data2099_4 from '../data/2099/4.json';
import data2099_5 from '../data/2099/5.json';
import data2099_6 from '../data/2099/6.json';
import data2099_7 from '../data/2099/7.json';
import data2099_8 from '../data/2099/8.json';
import data2099_9 from '../data/2099/9.json';
import data2099_10 from '../data/2099/10.json';
import data2099_11 from '../data/2099/11.json';
import data2099_12 from '../data/2099/12.json';

import data2100_1 from '../data/2100/1.json';
import data2100_2 from '../data/2100/2.json';
import data2100_3 from '../data/2100/3.json';
import data2100_4 from '../data/2100/4.json';
import data2100_5 from '../data/2100/5.json';
import data2100_6 from '../data/2100/6.json';
import data2100_7 from '../data/2100/7.json';
import data2100_8 from '../data/2100/8.json';
import data2100_9 from '../data/2100/9.json';
import data2100_10 from '../data/2100/10.json';
import data2100_11 from '../data/2100/11.json';
import data2100_12 from '../data/2100/12.json';

export const modules = {
  "1992/1": data1992_1,
  "1992/2": data1992_2,
  "1992/3": data1992_3,
  "1992/4": data1992_4,
  "1992/5": data1992_5,
  "1992/6": data1992_6,
  "1992/7": data1992_7,
  "1992/8": data1992_8,
  "1992/9": data1992_9,
  "1992/10": data1992_10,
  "1992/11": data1992_11,
  "1992/12": data1992_12,
  "1993/1": data1993_1,
  "1993/2": data1993_2,
  "1993/3": data1993_3,
  "1993/4": data1993_4,
  "1993/5": data1993_5,
  "1993/6": data1993_6,
  "1993/7": data1993_7,
  "1993/8": data1993_8,
  "1993/9": data1993_9,
  "1993/10": data1993_10,
  "1993/11": data1993_11,
  "1993/12": data1993_12,
  "1994/1": data1994_1,
  "1994/2": data1994_2,
  "1994/3": data1994_3,
  "1994/4": data1994_4,
  "1994/5": data1994_5,
  "1994/6": data1994_6,
  "1994/7": data1994_7,
  "1994/8": data1994_8,
  "1994/9": data1994_9,
  "1994/10": data1994_10,
  "1994/11": data1994_11,
  "1994/12": data1994_12,
  "1995/1": data1995_1,
  "1995/2": data1995_2,
  "1995/3": data1995_3,
  "1995/4": data1995_4,
  "1995/5": data1995_5,
  "1995/6": data1995_6,
  "1995/7": data1995_7,
  "1995/8": data1995_8,
  "1995/9": data1995_9,
  "1995/10": data1995_10,
  "1995/11": data1995_11,
  "1995/12": data1995_12,
  "1996/1": data1996_1,
  "1996/2": data1996_2,
  "1996/3": data1996_3,
  "1996/4": data1996_4,
  "1996/5": data1996_5,
  "1996/6": data1996_6,
  "1996/7": data1996_7,
  "1996/8": data1996_8,
  "1996/9": data1996_9,
  "1996/10": data1996_10,
  "1996/11": data1996_11,
  "1996/12": data1996_12,
  "1997/1": data1997_1,
  "1997/2": data1997_2,
  "1997/3": data1997_3,
  "1997/4": data1997_4,
  "1997/5": data1997_5,
  "1997/6": data1997_6,
  "1997/7": data1997_7,
  "1997/8": data1997_8,
  "1997/9": data1997_9,
  "1997/10": data1997_10,
  "1997/11": data1997_11,
  "1997/12": data1997_12,
  "1998/1": data1998_1,
  "1998/2": data1998_2,
  "1998/3": data1998_3,
  "1998/4": data1998_4,
  "1998/5": data1998_5,
  "1998/6": data1998_6,
  "1998/7": data1998_7,
  "1998/8": data1998_8,
  "1998/9": data1998_9,
  "1998/10": data1998_10,
  "1998/11": data1998_11,
  "1998/12": data1998_12,
  "1999/1": data1999_1,
  "1999/2": data1999_2,
  "1999/3": data1999_3,
  "1999/4": data1999_4,
  "1999/5": data1999_5,
  "1999/6": data1999_6,
  "1999/7": data1999_7,
  "1999/8": data1999_8,
  "1999/9": data1999_9,
  "1999/10": data1999_10,
  "1999/11": data1999_11,
  "1999/12": data1999_12,
  "2000/1": data2000_1,
  "2000/2": data2000_2,
  "2000/3": data2000_3,
  "2000/4": data2000_4,
  "2000/5": data2000_5,
  "2000/6": data2000_6,
  "2000/7": data2000_7,
  "2000/8": data2000_8,
  "2000/9": data2000_9,
  "2000/10": data2000_10,
  "2000/11": data2000_11,
  "2000/12": data2000_12,
  "2001/1": data2001_1,
  "2001/2": data2001_2,
  "2001/3": data2001_3,
  "2001/4": data2001_4,
  "2001/5": data2001_5,
  "2001/6": data2001_6,
  "2001/7": data2001_7,
  "2001/8": data2001_8,
  "2001/9": data2001_9,
  "2001/10": data2001_10,
  "2001/11": data2001_11,
  "2001/12": data2001_12,
  "2002/1": data2002_1,
  "2002/2": data2002_2,
  "2002/3": data2002_3,
  "2002/4": data2002_4,
  "2002/5": data2002_5,
  "2002/6": data2002_6,
  "2002/7": data2002_7,
  "2002/8": data2002_8,
  "2002/9": data2002_9,
  "2002/10": data2002_10,
  "2002/11": data2002_11,
  "2002/12": data2002_12,
  "2003/1": data2003_1,
  "2003/2": data2003_2,
  "2003/3": data2003_3,
  "2003/4": data2003_4,
  "2003/5": data2003_5,
  "2003/6": data2003_6,
  "2003/7": data2003_7,
  "2003/8": data2003_8,
  "2003/9": data2003_9,
  "2003/10": data2003_10,
  "2003/11": data2003_11,
  "2003/12": data2003_12,
  "2004/1": data2004_1,
  "2004/2": data2004_2,
  "2004/3": data2004_3,
  "2004/4": data2004_4,
  "2004/5": data2004_5,
  "2004/6": data2004_6,
  "2004/7": data2004_7,
  "2004/8": data2004_8,
  "2004/9": data2004_9,
  "2004/10": data2004_10,
  "2004/11": data2004_11,
  "2004/12": data2004_12,
  "2005/1": data2005_1,
  "2005/2": data2005_2,
  "2005/3": data2005_3,
  "2005/4": data2005_4,
  "2005/5": data2005_5,
  "2005/6": data2005_6,
  "2005/7": data2005_7,
  "2005/8": data2005_8,
  "2005/9": data2005_9,
  "2005/10": data2005_10,
  "2005/11": data2005_11,
  "2005/12": data2005_12,
  "2006/1": data2006_1,
  "2006/2": data2006_2,
  "2006/3": data2006_3,
  "2006/4": data2006_4,
  "2006/5": data2006_5,
  "2006/6": data2006_6,
  "2006/7": data2006_7,
  "2006/8": data2006_8,
  "2006/9": data2006_9,
  "2006/10": data2006_10,
  "2006/11": data2006_11,
  "2006/12": data2006_12,
  "2007/1": data2007_1,
  "2007/2": data2007_2,
  "2007/3": data2007_3,
  "2007/4": data2007_4,
  "2007/5": data2007_5,
  "2007/6": data2007_6,
  "2007/7": data2007_7,
  "2007/8": data2007_8,
  "2007/9": data2007_9,
  "2007/10": data2007_10,
  "2007/11": data2007_11,
  "2007/12": data2007_12,
  "2008/1": data2008_1,
  "2008/2": data2008_2,
  "2008/3": data2008_3,
  "2008/4": data2008_4,
  "2008/5": data2008_5,
  "2008/6": data2008_6,
  "2008/7": data2008_7,
  "2008/8": data2008_8,
  "2008/9": data2008_9,
  "2008/10": data2008_10,
  "2008/11": data2008_11,
  "2008/12": data2008_12,
  "2009/1": data2009_1,
  "2009/2": data2009_2,
  "2009/3": data2009_3,
  "2009/4": data2009_4,
  "2009/5": data2009_5,
  "2009/6": data2009_6,
  "2009/7": data2009_7,
  "2009/8": data2009_8,
  "2009/9": data2009_9,
  "2009/10": data2009_10,
  "2009/11": data2009_11,
  "2009/12": data2009_12,
  "2010/1": data2010_1,
  "2010/2": data2010_2,
  "2010/3": data2010_3,
  "2010/4": data2010_4,
  "2010/5": data2010_5,
  "2010/6": data2010_6,
  "2010/7": data2010_7,
  "2010/8": data2010_8,
  "2010/9": data2010_9,
  "2010/10": data2010_10,
  "2010/11": data2010_11,
  "2010/12": data2010_12,
  "2011/1": data2011_1,
  "2011/2": data2011_2,
  "2011/3": data2011_3,
  "2011/4": data2011_4,
  "2011/5": data2011_5,
  "2011/6": data2011_6,
  "2011/7": data2011_7,
  "2011/8": data2011_8,
  "2011/9": data2011_9,
  "2011/10": data2011_10,
  "2011/11": data2011_11,
  "2011/12": data2011_12,
  "2012/1": data2012_1,
  "2012/2": data2012_2,
  "2012/3": data2012_3,
  "2012/4": data2012_4,
  "2012/5": data2012_5,
  "2012/6": data2012_6,
  "2012/7": data2012_7,
  "2012/8": data2012_8,
  "2012/9": data2012_9,
  "2012/10": data2012_10,
  "2012/11": data2012_11,
  "2012/12": data2012_12,
  "2013/1": data2013_1,
  "2013/2": data2013_2,
  "2013/3": data2013_3,
  "2013/4": data2013_4,
  "2013/5": data2013_5,
  "2013/6": data2013_6,
  "2013/7": data2013_7,
  "2013/8": data2013_8,
  "2013/9": data2013_9,
  "2013/10": data2013_10,
  "2013/11": data2013_11,
  "2013/12": data2013_12,
  "2014/1": data2014_1,
  "2014/2": data2014_2,
  "2014/3": data2014_3,
  "2014/4": data2014_4,
  "2014/5": data2014_5,
  "2014/6": data2014_6,
  "2014/7": data2014_7,
  "2014/8": data2014_8,
  "2014/9": data2014_9,
  "2014/10": data2014_10,
  "2014/11": data2014_11,
  "2014/12": data2014_12,
  "2015/1": data2015_1,
  "2015/2": data2015_2,
  "2015/3": data2015_3,
  "2015/4": data2015_4,
  "2015/5": data2015_5,
  "2015/6": data2015_6,
  "2015/7": data2015_7,
  "2015/8": data2015_8,
  "2015/9": data2015_9,
  "2015/10": data2015_10,
  "2015/11": data2015_11,
  "2015/12": data2015_12,
  "2016/1": data2016_1,
  "2016/2": data2016_2,
  "2016/3": data2016_3,
  "2016/4": data2016_4,
  "2016/5": data2016_5,
  "2016/6": data2016_6,
  "2016/7": data2016_7,
  "2016/8": data2016_8,
  "2016/9": data2016_9,
  "2016/10": data2016_10,
  "2016/11": data2016_11,
  "2016/12": data2016_12,
  "2017/1": data2017_1,
  "2017/2": data2017_2,
  "2017/3": data2017_3,
  "2017/4": data2017_4,
  "2017/5": data2017_5,
  "2017/6": data2017_6,
  "2017/7": data2017_7,
  "2017/8": data2017_8,
  "2017/9": data2017_9,
  "2017/10": data2017_10,
  "2017/11": data2017_11,
  "2017/12": data2017_12,
  "2018/1": data2018_1,
  "2018/2": data2018_2,
  "2018/3": data2018_3,
  "2018/4": data2018_4,
  "2018/5": data2018_5,
  "2018/6": data2018_6,
  "2018/7": data2018_7,
  "2018/8": data2018_8,
  "2018/9": data2018_9,
  "2018/10": data2018_10,
  "2018/11": data2018_11,
  "2018/12": data2018_12,
  "2019/1": data2019_1,
  "2019/2": data2019_2,
  "2019/3": data2019_3,
  "2019/4": data2019_4,
  "2019/5": data2019_5,
  "2019/6": data2019_6,
  "2019/7": data2019_7,
  "2019/8": data2019_8,
  "2019/9": data2019_9,
  "2019/10": data2019_10,
  "2019/11": data2019_11,
  "2019/12": data2019_12,
  "2020/1": data2020_1,
  "2020/2": data2020_2,
  "2020/3": data2020_3,
  "2020/4": data2020_4,
  "2020/5": data2020_5,
  "2020/6": data2020_6,
  "2020/7": data2020_7,
  "2020/8": data2020_8,
  "2020/9": data2020_9,
  "2020/10": data2020_10,
  "2020/11": data2020_11,
  "2020/12": data2020_12,
  "2021/1": data2021_1,
  "2021/2": data2021_2,
  "2021/3": data2021_3,
  "2021/4": data2021_4,
  "2021/5": data2021_5,
  "2021/6": data2021_6,
  "2021/7": data2021_7,
  "2021/8": data2021_8,
  "2021/9": data2021_9,
  "2021/10": data2021_10,
  "2021/11": data2021_11,
  "2021/12": data2021_12,
  "2022/1": data2022_1,
  "2022/2": data2022_2,
  "2022/3": data2022_3,
  "2022/4": data2022_4,
  "2022/5": data2022_5,
  "2022/6": data2022_6,
  "2022/7": data2022_7,
  "2022/8": data2022_8,
  "2022/9": data2022_9,
  "2022/10": data2022_10,
  "2022/11": data2022_11,
  "2022/12": data2022_12,
  "2023/1": data2023_1,
  "2023/2": data2023_2,
  "2023/3": data2023_3,
  "2023/4": data2023_4,
  "2023/5": data2023_5,
  "2023/6": data2023_6,
  "2023/7": data2023_7,
  "2023/8": data2023_8,
  "2023/9": data2023_9,
  "2023/10": data2023_10,
  "2023/11": data2023_11,
  "2023/12": data2023_12,
  "2024/1": data2024_1,
  "2024/2": data2024_2,
  "2024/3": data2024_3,
  "2024/4": data2024_4,
  "2024/5": data2024_5,
  "2024/6": data2024_6,
  "2024/7": data2024_7,
  "2024/8": data2024_8,
  "2024/9": data2024_9,
  "2024/10": data2024_10,
  "2024/11": data2024_11,
  "2024/12": data2024_12,
  "2025/1": data2025_1,
  "2025/2": data2025_2,
  "2025/3": data2025_3,
  "2025/4": data2025_4,
  "2025/5": data2025_5,
  "2025/6": data2025_6,
  "2025/7": data2025_7,
  "2025/8": data2025_8,
  "2025/9": data2025_9,
  "2025/10": data2025_10,
  "2025/11": data2025_11,
  "2025/12": data2025_12,
  "2026/1": data2026_1,
  "2026/2": data2026_2,
  "2026/3": data2026_3,
  "2026/4": data2026_4,
  "2026/5": data2026_5,
  "2026/6": data2026_6,
  "2026/7": data2026_7,
  "2026/8": data2026_8,
  "2026/9": data2026_9,
  "2026/10": data2026_10,
  "2026/11": data2026_11,
  "2026/12": data2026_12,
  "2027/1": data2027_1,
  "2027/2": data2027_2,
  "2027/3": data2027_3,
  "2027/4": data2027_4,
  "2027/5": data2027_5,
  "2027/6": data2027_6,
  "2027/7": data2027_7,
  "2027/8": data2027_8,
  "2027/9": data2027_9,
  "2027/10": data2027_10,
  "2027/11": data2027_11,
  "2027/12": data2027_12,
  "2028/1": data2028_1,
  "2028/2": data2028_2,
  "2028/3": data2028_3,
  "2028/4": data2028_4,
  "2028/5": data2028_5,
  "2028/6": data2028_6,
  "2028/7": data2028_7,
  "2028/8": data2028_8,
  "2028/9": data2028_9,
  "2028/10": data2028_10,
  "2028/11": data2028_11,
  "2028/12": data2028_12,
  "2029/1": data2029_1,
  "2029/2": data2029_2,
  "2029/3": data2029_3,
  "2029/4": data2029_4,
  "2029/5": data2029_5,
  "2029/6": data2029_6,
  "2029/7": data2029_7,
  "2029/8": data2029_8,
  "2029/9": data2029_9,
  "2029/10": data2029_10,
  "2029/11": data2029_11,
  "2029/12": data2029_12,
  "2030/1": data2030_1,
  "2030/2": data2030_2,
  "2030/3": data2030_3,
  "2030/4": data2030_4,
  "2030/5": data2030_5,
  "2030/6": data2030_6,
  "2030/7": data2030_7,
  "2030/8": data2030_8,
  "2030/9": data2030_9,
  "2030/10": data2030_10,
  "2030/11": data2030_11,
  "2030/12": data2030_12,
  "2031/1": data2031_1,
  "2031/2": data2031_2,
  "2031/3": data2031_3,
  "2031/4": data2031_4,
  "2031/5": data2031_5,
  "2031/6": data2031_6,
  "2031/7": data2031_7,
  "2031/8": data2031_8,
  "2031/9": data2031_9,
  "2031/10": data2031_10,
  "2031/11": data2031_11,
  "2031/12": data2031_12,
  "2032/1": data2032_1,
  "2032/2": data2032_2,
  "2032/3": data2032_3,
  "2032/4": data2032_4,
  "2032/5": data2032_5,
  "2032/6": data2032_6,
  "2032/7": data2032_7,
  "2032/8": data2032_8,
  "2032/9": data2032_9,
  "2032/10": data2032_10,
  "2032/11": data2032_11,
  "2032/12": data2032_12,
  "2033/1": data2033_1,
  "2033/2": data2033_2,
  "2033/3": data2033_3,
  "2033/4": data2033_4,
  "2033/5": data2033_5,
  "2033/6": data2033_6,
  "2033/7": data2033_7,
  "2033/8": data2033_8,
  "2033/9": data2033_9,
  "2033/10": data2033_10,
  "2033/11": data2033_11,
  "2033/12": data2033_12,
  "2034/1": data2034_1,
  "2034/2": data2034_2,
  "2034/3": data2034_3,
  "2034/4": data2034_4,
  "2034/5": data2034_5,
  "2034/6": data2034_6,
  "2034/7": data2034_7,
  "2034/8": data2034_8,
  "2034/9": data2034_9,
  "2034/10": data2034_10,
  "2034/11": data2034_11,
  "2034/12": data2034_12,
  "2035/1": data2035_1,
  "2035/2": data2035_2,
  "2035/3": data2035_3,
  "2035/4": data2035_4,
  "2035/5": data2035_5,
  "2035/6": data2035_6,
  "2035/7": data2035_7,
  "2035/8": data2035_8,
  "2035/9": data2035_9,
  "2035/10": data2035_10,
  "2035/11": data2035_11,
  "2035/12": data2035_12,
  "2036/1": data2036_1,
  "2036/2": data2036_2,
  "2036/3": data2036_3,
  "2036/4": data2036_4,
  "2036/5": data2036_5,
  "2036/6": data2036_6,
  "2036/7": data2036_7,
  "2036/8": data2036_8,
  "2036/9": data2036_9,
  "2036/10": data2036_10,
  "2036/11": data2036_11,
  "2036/12": data2036_12,
  "2037/1": data2037_1,
  "2037/2": data2037_2,
  "2037/3": data2037_3,
  "2037/4": data2037_4,
  "2037/5": data2037_5,
  "2037/6": data2037_6,
  "2037/7": data2037_7,
  "2037/8": data2037_8,
  "2037/9": data2037_9,
  "2037/10": data2037_10,
  "2037/11": data2037_11,
  "2037/12": data2037_12,
  "2038/1": data2038_1,
  "2038/2": data2038_2,
  "2038/3": data2038_3,
  "2038/4": data2038_4,
  "2038/5": data2038_5,
  "2038/6": data2038_6,
  "2038/7": data2038_7,
  "2038/8": data2038_8,
  "2038/9": data2038_9,
  "2038/10": data2038_10,
  "2038/11": data2038_11,
  "2038/12": data2038_12,
  "2039/1": data2039_1,
  "2039/2": data2039_2,
  "2039/3": data2039_3,
  "2039/4": data2039_4,
  "2039/5": data2039_5,
  "2039/6": data2039_6,
  "2039/7": data2039_7,
  "2039/8": data2039_8,
  "2039/9": data2039_9,
  "2039/10": data2039_10,
  "2039/11": data2039_11,
  "2039/12": data2039_12,
  "2040/1": data2040_1,
  "2040/2": data2040_2,
  "2040/3": data2040_3,
  "2040/4": data2040_4,
  "2040/5": data2040_5,
  "2040/6": data2040_6,
  "2040/7": data2040_7,
  "2040/8": data2040_8,
  "2040/9": data2040_9,
  "2040/10": data2040_10,
  "2040/11": data2040_11,
  "2040/12": data2040_12,
  "2041/1": data2041_1,
  "2041/2": data2041_2,
  "2041/3": data2041_3,
  "2041/4": data2041_4,
  "2041/5": data2041_5,
  "2041/6": data2041_6,
  "2041/7": data2041_7,
  "2041/8": data2041_8,
  "2041/9": data2041_9,
  "2041/10": data2041_10,
  "2041/11": data2041_11,
  "2041/12": data2041_12,
  "2042/1": data2042_1,
  "2042/2": data2042_2,
  "2042/3": data2042_3,
  "2042/4": data2042_4,
  "2042/5": data2042_5,
  "2042/6": data2042_6,
  "2042/7": data2042_7,
  "2042/8": data2042_8,
  "2042/9": data2042_9,
  "2042/10": data2042_10,
  "2042/11": data2042_11,
  "2042/12": data2042_12,
  "2043/1": data2043_1,
  "2043/2": data2043_2,
  "2043/3": data2043_3,
  "2043/4": data2043_4,
  "2043/5": data2043_5,
  "2043/6": data2043_6,
  "2043/7": data2043_7,
  "2043/8": data2043_8,
  "2043/9": data2043_9,
  "2043/10": data2043_10,
  "2043/11": data2043_11,
  "2043/12": data2043_12,
  "2044/1": data2044_1,
  "2044/2": data2044_2,
  "2044/3": data2044_3,
  "2044/4": data2044_4,
  "2044/5": data2044_5,
  "2044/6": data2044_6,
  "2044/7": data2044_7,
  "2044/8": data2044_8,
  "2044/9": data2044_9,
  "2044/10": data2044_10,
  "2044/11": data2044_11,
  "2044/12": data2044_12,
  "2045/1": data2045_1,
  "2045/2": data2045_2,
  "2045/3": data2045_3,
  "2045/4": data2045_4,
  "2045/5": data2045_5,
  "2045/6": data2045_6,
  "2045/7": data2045_7,
  "2045/8": data2045_8,
  "2045/9": data2045_9,
  "2045/10": data2045_10,
  "2045/11": data2045_11,
  "2045/12": data2045_12,
  "2046/1": data2046_1,
  "2046/2": data2046_2,
  "2046/3": data2046_3,
  "2046/4": data2046_4,
  "2046/5": data2046_5,
  "2046/6": data2046_6,
  "2046/7": data2046_7,
  "2046/8": data2046_8,
  "2046/9": data2046_9,
  "2046/10": data2046_10,
  "2046/11": data2046_11,
  "2046/12": data2046_12,
  "2047/1": data2047_1,
  "2047/2": data2047_2,
  "2047/3": data2047_3,
  "2047/4": data2047_4,
  "2047/5": data2047_5,
  "2047/6": data2047_6,
  "2047/7": data2047_7,
  "2047/8": data2047_8,
  "2047/9": data2047_9,
  "2047/10": data2047_10,
  "2047/11": data2047_11,
  "2047/12": data2047_12,
  "2048/1": data2048_1,
  "2048/2": data2048_2,
  "2048/3": data2048_3,
  "2048/4": data2048_4,
  "2048/5": data2048_5,
  "2048/6": data2048_6,
  "2048/7": data2048_7,
  "2048/8": data2048_8,
  "2048/9": data2048_9,
  "2048/10": data2048_10,
  "2048/11": data2048_11,
  "2048/12": data2048_12,
  "2049/1": data2049_1,
  "2049/2": data2049_2,
  "2049/3": data2049_3,
  "2049/4": data2049_4,
  "2049/5": data2049_5,
  "2049/6": data2049_6,
  "2049/7": data2049_7,
  "2049/8": data2049_8,
  "2049/9": data2049_9,
  "2049/10": data2049_10,
  "2049/11": data2049_11,
  "2049/12": data2049_12,
  "2050/1": data2050_1,
  "2050/2": data2050_2,
  "2050/3": data2050_3,
  "2050/4": data2050_4,
  "2050/5": data2050_5,
  "2050/6": data2050_6,
  "2050/7": data2050_7,
  "2050/8": data2050_8,
  "2050/9": data2050_9,
  "2050/10": data2050_10,
  "2050/11": data2050_11,
  "2050/12": data2050_12,
  "2051/1": data2051_1,
  "2051/2": data2051_2,
  "2051/3": data2051_3,
  "2051/4": data2051_4,
  "2051/5": data2051_5,
  "2051/6": data2051_6,
  "2051/7": data2051_7,
  "2051/8": data2051_8,
  "2051/9": data2051_9,
  "2051/10": data2051_10,
  "2051/11": data2051_11,
  "2051/12": data2051_12,
  "2052/1": data2052_1,
  "2052/2": data2052_2,
  "2052/3": data2052_3,
  "2052/4": data2052_4,
  "2052/5": data2052_5,
  "2052/6": data2052_6,
  "2052/7": data2052_7,
  "2052/8": data2052_8,
  "2052/9": data2052_9,
  "2052/10": data2052_10,
  "2052/11": data2052_11,
  "2052/12": data2052_12,
  "2053/1": data2053_1,
  "2053/2": data2053_2,
  "2053/3": data2053_3,
  "2053/4": data2053_4,
  "2053/5": data2053_5,
  "2053/6": data2053_6,
  "2053/7": data2053_7,
  "2053/8": data2053_8,
  "2053/9": data2053_9,
  "2053/10": data2053_10,
  "2053/11": data2053_11,
  "2053/12": data2053_12,
  "2054/1": data2054_1,
  "2054/2": data2054_2,
  "2054/3": data2054_3,
  "2054/4": data2054_4,
  "2054/5": data2054_5,
  "2054/6": data2054_6,
  "2054/7": data2054_7,
  "2054/8": data2054_8,
  "2054/9": data2054_9,
  "2054/10": data2054_10,
  "2054/11": data2054_11,
  "2054/12": data2054_12,
  "2055/1": data2055_1,
  "2055/2": data2055_2,
  "2055/3": data2055_3,
  "2055/4": data2055_4,
  "2055/5": data2055_5,
  "2055/6": data2055_6,
  "2055/7": data2055_7,
  "2055/8": data2055_8,
  "2055/9": data2055_9,
  "2055/10": data2055_10,
  "2055/11": data2055_11,
  "2055/12": data2055_12,
  "2056/1": data2056_1,
  "2056/2": data2056_2,
  "2056/3": data2056_3,
  "2056/4": data2056_4,
  "2056/5": data2056_5,
  "2056/6": data2056_6,
  "2056/7": data2056_7,
  "2056/8": data2056_8,
  "2056/9": data2056_9,
  "2056/10": data2056_10,
  "2056/11": data2056_11,
  "2056/12": data2056_12,
  "2057/1": data2057_1,
  "2057/2": data2057_2,
  "2057/3": data2057_3,
  "2057/4": data2057_4,
  "2057/5": data2057_5,
  "2057/6": data2057_6,
  "2057/7": data2057_7,
  "2057/8": data2057_8,
  "2057/9": data2057_9,
  "2057/10": data2057_10,
  "2057/11": data2057_11,
  "2057/12": data2057_12,
  "2058/1": data2058_1,
  "2058/2": data2058_2,
  "2058/3": data2058_3,
  "2058/4": data2058_4,
  "2058/5": data2058_5,
  "2058/6": data2058_6,
  "2058/7": data2058_7,
  "2058/8": data2058_8,
  "2058/9": data2058_9,
  "2058/10": data2058_10,
  "2058/11": data2058_11,
  "2058/12": data2058_12,
  "2059/1": data2059_1,
  "2059/2": data2059_2,
  "2059/3": data2059_3,
  "2059/4": data2059_4,
  "2059/5": data2059_5,
  "2059/6": data2059_6,
  "2059/7": data2059_7,
  "2059/8": data2059_8,
  "2059/9": data2059_9,
  "2059/10": data2059_10,
  "2059/11": data2059_11,
  "2059/12": data2059_12,
  "2060/1": data2060_1,
  "2060/2": data2060_2,
  "2060/3": data2060_3,
  "2060/4": data2060_4,
  "2060/5": data2060_5,
  "2060/6": data2060_6,
  "2060/7": data2060_7,
  "2060/8": data2060_8,
  "2060/9": data2060_9,
  "2060/10": data2060_10,
  "2060/11": data2060_11,
  "2060/12": data2060_12,
  "2061/1": data2061_1,
  "2061/2": data2061_2,
  "2061/3": data2061_3,
  "2061/4": data2061_4,
  "2061/5": data2061_5,
  "2061/6": data2061_6,
  "2061/7": data2061_7,
  "2061/8": data2061_8,
  "2061/9": data2061_9,
  "2061/10": data2061_10,
  "2061/11": data2061_11,
  "2061/12": data2061_12,
  "2062/1": data2062_1,
  "2062/2": data2062_2,
  "2062/3": data2062_3,
  "2062/4": data2062_4,
  "2062/5": data2062_5,
  "2062/6": data2062_6,
  "2062/7": data2062_7,
  "2062/8": data2062_8,
  "2062/9": data2062_9,
  "2062/10": data2062_10,
  "2062/11": data2062_11,
  "2062/12": data2062_12,
  "2063/1": data2063_1,
  "2063/2": data2063_2,
  "2063/3": data2063_3,
  "2063/4": data2063_4,
  "2063/5": data2063_5,
  "2063/6": data2063_6,
  "2063/7": data2063_7,
  "2063/8": data2063_8,
  "2063/9": data2063_9,
  "2063/10": data2063_10,
  "2063/11": data2063_11,
  "2063/12": data2063_12,
  "2064/1": data2064_1,
  "2064/2": data2064_2,
  "2064/3": data2064_3,
  "2064/4": data2064_4,
  "2064/5": data2064_5,
  "2064/6": data2064_6,
  "2064/7": data2064_7,
  "2064/8": data2064_8,
  "2064/9": data2064_9,
  "2064/10": data2064_10,
  "2064/11": data2064_11,
  "2064/12": data2064_12,
  "2065/1": data2065_1,
  "2065/2": data2065_2,
  "2065/3": data2065_3,
  "2065/4": data2065_4,
  "2065/5": data2065_5,
  "2065/6": data2065_6,
  "2065/7": data2065_7,
  "2065/8": data2065_8,
  "2065/9": data2065_9,
  "2065/10": data2065_10,
  "2065/11": data2065_11,
  "2065/12": data2065_12,
  "2066/1": data2066_1,
  "2066/2": data2066_2,
  "2066/3": data2066_3,
  "2066/4": data2066_4,
  "2066/5": data2066_5,
  "2066/6": data2066_6,
  "2066/7": data2066_7,
  "2066/8": data2066_8,
  "2066/9": data2066_9,
  "2066/10": data2066_10,
  "2066/11": data2066_11,
  "2066/12": data2066_12,
  "2067/1": data2067_1,
  "2067/2": data2067_2,
  "2067/3": data2067_3,
  "2067/4": data2067_4,
  "2067/5": data2067_5,
  "2067/6": data2067_6,
  "2067/7": data2067_7,
  "2067/8": data2067_8,
  "2067/9": data2067_9,
  "2067/10": data2067_10,
  "2067/11": data2067_11,
  "2067/12": data2067_12,
  "2068/1": data2068_1,
  "2068/2": data2068_2,
  "2068/3": data2068_3,
  "2068/4": data2068_4,
  "2068/5": data2068_5,
  "2068/6": data2068_6,
  "2068/7": data2068_7,
  "2068/8": data2068_8,
  "2068/9": data2068_9,
  "2068/10": data2068_10,
  "2068/11": data2068_11,
  "2068/12": data2068_12,
  "2069/1": data2069_1,
  "2069/2": data2069_2,
  "2069/3": data2069_3,
  "2069/4": data2069_4,
  "2069/5": data2069_5,
  "2069/6": data2069_6,
  "2069/7": data2069_7,
  "2069/8": data2069_8,
  "2069/9": data2069_9,
  "2069/10": data2069_10,
  "2069/11": data2069_11,
  "2069/12": data2069_12,
  "2070/1": data2070_1,
  "2070/2": data2070_2,
  "2070/3": data2070_3,
  "2070/4": data2070_4,
  "2070/5": data2070_5,
  "2070/6": data2070_6,
  "2070/7": data2070_7,
  "2070/8": data2070_8,
  "2070/9": data2070_9,
  "2070/10": data2070_10,
  "2070/11": data2070_11,
  "2070/12": data2070_12,
  "2071/1": data2071_1,
  "2071/2": data2071_2,
  "2071/3": data2071_3,
  "2071/4": data2071_4,
  "2071/5": data2071_5,
  "2071/6": data2071_6,
  "2071/7": data2071_7,
  "2071/8": data2071_8,
  "2071/9": data2071_9,
  "2071/10": data2071_10,
  "2071/11": data2071_11,
  "2071/12": data2071_12,
  "2072/1": data2072_1,
  "2072/2": data2072_2,
  "2072/3": data2072_3,
  "2072/4": data2072_4,
  "2072/5": data2072_5,
  "2072/6": data2072_6,
  "2072/7": data2072_7,
  "2072/8": data2072_8,
  "2072/9": data2072_9,
  "2072/10": data2072_10,
  "2072/11": data2072_11,
  "2072/12": data2072_12,
  "2073/1": data2073_1,
  "2073/2": data2073_2,
  "2073/3": data2073_3,
  "2073/4": data2073_4,
  "2073/5": data2073_5,
  "2073/6": data2073_6,
  "2073/7": data2073_7,
  "2073/8": data2073_8,
  "2073/9": data2073_9,
  "2073/10": data2073_10,
  "2073/11": data2073_11,
  "2073/12": data2073_12,
  "2074/1": data2074_1,
  "2074/2": data2074_2,
  "2074/3": data2074_3,
  "2074/4": data2074_4,
  "2074/5": data2074_5,
  "2074/6": data2074_6,
  "2074/7": data2074_7,
  "2074/8": data2074_8,
  "2074/9": data2074_9,
  "2074/10": data2074_10,
  "2074/11": data2074_11,
  "2074/12": data2074_12,
  "2075/1": data2075_1,
  "2075/2": data2075_2,
  "2075/3": data2075_3,
  "2075/4": data2075_4,
  "2075/5": data2075_5,
  "2075/6": data2075_6,
  "2075/7": data2075_7,
  "2075/8": data2075_8,
  "2075/9": data2075_9,
  "2075/10": data2075_10,
  "2075/11": data2075_11,
  "2075/12": data2075_12,
  "2076/1": data2076_1,
  "2076/2": data2076_2,
  "2076/3": data2076_3,
  "2076/4": data2076_4,
  "2076/5": data2076_5,
  "2076/6": data2076_6,
  "2076/7": data2076_7,
  "2076/8": data2076_8,
  "2076/9": data2076_9,
  "2076/10": data2076_10,
  "2076/11": data2076_11,
  "2076/12": data2076_12,
  "2077/1": data2077_1,
  "2077/2": data2077_2,
  "2077/3": data2077_3,
  "2077/4": data2077_4,
  "2077/5": data2077_5,
  "2077/6": data2077_6,
  "2077/7": data2077_7,
  "2077/8": data2077_8,
  "2077/9": data2077_9,
  "2077/10": data2077_10,
  "2077/11": data2077_11,
  "2077/12": data2077_12,
  "2078/1": data2078_1,
  "2078/2": data2078_2,
  "2078/3": data2078_3,
  "2078/4": data2078_4,
  "2078/5": data2078_5,
  "2078/6": data2078_6,
  "2078/7": data2078_7,
  "2078/8": data2078_8,
  "2078/9": data2078_9,
  "2078/10": data2078_10,
  "2078/11": data2078_11,
  "2078/12": data2078_12,
  "2079/1": data2079_1,
  "2079/2": data2079_2,
  "2079/3": data2079_3,
  "2079/4": data2079_4,
  "2079/5": data2079_5,
  "2079/6": data2079_6,
  "2079/7": data2079_7,
  "2079/8": data2079_8,
  "2079/9": data2079_9,
  "2079/10": data2079_10,
  "2079/11": data2079_11,
  "2079/12": data2079_12,
  "2080/1": data2080_1,
  "2080/2": data2080_2,
  "2080/3": data2080_3,
  "2080/4": data2080_4,
  "2080/5": data2080_5,
  "2080/6": data2080_6,
  "2080/7": data2080_7,
  "2080/8": data2080_8,
  "2080/9": data2080_9,
  "2080/10": data2080_10,
  "2080/11": data2080_11,
  "2080/12": data2080_12,
  "2081/1": data2081_1,
  "2081/2": data2081_2,
  "2081/3": data2081_3,
  "2081/4": data2081_4,
  "2081/5": data2081_5,
  "2081/6": data2081_6,
  "2081/7": data2081_7,
  "2081/8": data2081_8,
  "2081/9": data2081_9,
  "2081/10": data2081_10,
  "2081/11": data2081_11,
  "2081/12": data2081_12,
  "2082/1": data2082_1,
  "2082/2": data2082_2,
  "2082/3": data2082_3,
  "2082/4": data2082_4,
  "2082/5": data2082_5,
  "2082/6": data2082_6,
  "2082/7": data2082_7,
  "2082/8": data2082_8,
  "2082/9": data2082_9,
  "2082/10": data2082_10,
  "2082/11": data2082_11,
  "2082/12": data2082_12,
  "2083/1": data2083_1,
  "2083/2": data2083_2,
  "2083/3": data2083_3,
  "2083/4": data2083_4,
  "2083/5": data2083_5,
  "2083/6": data2083_6,
  "2083/7": data2083_7,
  "2083/8": data2083_8,
  "2083/9": data2083_9,
  "2083/10": data2083_10,
  "2083/11": data2083_11,
  "2083/12": data2083_12,
  "2084/1": data2084_1,
  "2084/2": data2084_2,
  "2084/3": data2084_3,
  "2084/4": data2084_4,
  "2084/5": data2084_5,
  "2084/6": data2084_6,
  "2084/7": data2084_7,
  "2084/8": data2084_8,
  "2084/9": data2084_9,
  "2084/10": data2084_10,
  "2084/11": data2084_11,
  "2084/12": data2084_12,
  "2085/1": data2085_1,
  "2085/2": data2085_2,
  "2085/3": data2085_3,
  "2085/4": data2085_4,
  "2085/5": data2085_5,
  "2085/6": data2085_6,
  "2085/7": data2085_7,
  "2085/8": data2085_8,
  "2085/9": data2085_9,
  "2085/10": data2085_10,
  "2085/11": data2085_11,
  "2085/12": data2085_12,
  "2086/1": data2086_1,
  "2086/2": data2086_2,
  "2086/3": data2086_3,
  "2086/4": data2086_4,
  "2086/5": data2086_5,
  "2086/6": data2086_6,
  "2086/7": data2086_7,
  "2086/8": data2086_8,
  "2086/9": data2086_9,
  "2086/10": data2086_10,
  "2086/11": data2086_11,
  "2086/12": data2086_12,
  "2087/1": data2087_1,
  "2087/2": data2087_2,
  "2087/3": data2087_3,
  "2087/4": data2087_4,
  "2087/5": data2087_5,
  "2087/6": data2087_6,
  "2087/7": data2087_7,
  "2087/8": data2087_8,
  "2087/9": data2087_9,
  "2087/10": data2087_10,
  "2087/11": data2087_11,
  "2087/12": data2087_12,
  "2088/1": data2088_1,
  "2088/2": data2088_2,
  "2088/3": data2088_3,
  "2088/4": data2088_4,
  "2088/5": data2088_5,
  "2088/6": data2088_6,
  "2088/7": data2088_7,
  "2088/8": data2088_8,
  "2088/9": data2088_9,
  "2088/10": data2088_10,
  "2088/11": data2088_11,
  "2088/12": data2088_12,
  "2089/1": data2089_1,
  "2089/2": data2089_2,
  "2089/3": data2089_3,
  "2089/4": data2089_4,
  "2089/5": data2089_5,
  "2089/6": data2089_6,
  "2089/7": data2089_7,
  "2089/8": data2089_8,
  "2089/9": data2089_9,
  "2089/10": data2089_10,
  "2089/11": data2089_11,
  "2089/12": data2089_12,
  "2090/1": data2090_1,
  "2090/2": data2090_2,
  "2090/3": data2090_3,
  "2090/4": data2090_4,
  "2090/5": data2090_5,
  "2090/6": data2090_6,
  "2090/7": data2090_7,
  "2090/8": data2090_8,
  "2090/9": data2090_9,
  "2090/10": data2090_10,
  "2090/11": data2090_11,
  "2090/12": data2090_12,
  "2091/1": data2091_1,
  "2091/2": data2091_2,
  "2091/3": data2091_3,
  "2091/4": data2091_4,
  "2091/5": data2091_5,
  "2091/6": data2091_6,
  "2091/7": data2091_7,
  "2091/8": data2091_8,
  "2091/9": data2091_9,
  "2091/10": data2091_10,
  "2091/11": data2091_11,
  "2091/12": data2091_12,
  "2092/1": data2092_1,
  "2092/2": data2092_2,
  "2092/3": data2092_3,
  "2092/4": data2092_4,
  "2092/5": data2092_5,
  "2092/6": data2092_6,
  "2092/7": data2092_7,
  "2092/8": data2092_8,
  "2092/9": data2092_9,
  "2092/10": data2092_10,
  "2092/11": data2092_11,
  "2092/12": data2092_12,
  "2093/1": data2093_1,
  "2093/2": data2093_2,
  "2093/3": data2093_3,
  "2093/4": data2093_4,
  "2093/5": data2093_5,
  "2093/6": data2093_6,
  "2093/7": data2093_7,
  "2093/8": data2093_8,
  "2093/9": data2093_9,
  "2093/10": data2093_10,
  "2093/11": data2093_11,
  "2093/12": data2093_12,
  "2094/1": data2094_1,
  "2094/2": data2094_2,
  "2094/3": data2094_3,
  "2094/4": data2094_4,
  "2094/5": data2094_5,
  "2094/6": data2094_6,
  "2094/7": data2094_7,
  "2094/8": data2094_8,
  "2094/9": data2094_9,
  "2094/10": data2094_10,
  "2094/11": data2094_11,
  "2094/12": data2094_12,
  "2095/1": data2095_1,
  "2095/2": data2095_2,
  "2095/3": data2095_3,
  "2095/4": data2095_4,
  "2095/5": data2095_5,
  "2095/6": data2095_6,
  "2095/7": data2095_7,
  "2095/8": data2095_8,
  "2095/9": data2095_9,
  "2095/10": data2095_10,
  "2095/11": data2095_11,
  "2095/12": data2095_12,
  "2096/1": data2096_1,
  "2096/2": data2096_2,
  "2096/3": data2096_3,
  "2096/4": data2096_4,
  "2096/5": data2096_5,
  "2096/6": data2096_6,
  "2096/7": data2096_7,
  "2096/8": data2096_8,
  "2096/9": data2096_9,
  "2096/10": data2096_10,
  "2096/11": data2096_11,
  "2096/12": data2096_12,
  "2097/1": data2097_1,
  "2097/2": data2097_2,
  "2097/3": data2097_3,
  "2097/4": data2097_4,
  "2097/5": data2097_5,
  "2097/6": data2097_6,
  "2097/7": data2097_7,
  "2097/8": data2097_8,
  "2097/9": data2097_9,
  "2097/10": data2097_10,
  "2097/11": data2097_11,
  "2097/12": data2097_12,
  "2098/1": data2098_1,
  "2098/2": data2098_2,
  "2098/3": data2098_3,
  "2098/4": data2098_4,
  "2098/5": data2098_5,
  "2098/6": data2098_6,
  "2098/7": data2098_7,
  "2098/8": data2098_8,
  "2098/9": data2098_9,
  "2098/10": data2098_10,
  "2098/11": data2098_11,
  "2098/12": data2098_12,
  "2099/1": data2099_1,
  "2099/2": data2099_2,
  "2099/3": data2099_3,
  "2099/4": data2099_4,
  "2099/5": data2099_5,
  "2099/6": data2099_6,
  "2099/7": data2099_7,
  "2099/8": data2099_8,
  "2099/9": data2099_9,
  "2099/10": data2099_10,
  "2099/11": data2099_11,
  "2099/12": data2099_12,
  "2100/1": data2100_1,
  "2100/2": data2100_2,
  "2100/3": data2100_3,
  "2100/4": data2100_4,
  "2100/5": data2100_5,
  "2100/6": data2100_6,
  "2100/7": data2100_7,
  "2100/8": data2100_8,
  "2100/9": data2100_9,
  "2100/10": data2100_10,
  "2100/11": data2100_11,
  "2100/12": data2100_12,
};

export async function getNepaliDateData(year, month) {
  const normalizedMonth = String(Number(month));
  const key = `${year}/${normalizedMonth}`;
  if (modules[key]) {
    return modules[key];
  } else {
    throw new Error(`Data for year ${year} and month ${month} not found.`);
  }
}